---
title: "Untitled"
author: "Jacob Tarnowski"
date: "June 2, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Load Packages
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(EnvStats)
```

```{r}
load("C:/Users/Student/Desktop/Jake Tarnowski Simulations/Phase 3/Master Model.Rdata")
df.Rho <- df.Rho %>%
  filter(Rho == .2)
```



#Parameters of the simulation
```{r}
mu = 0
sd = 1
rho = .2
num_of_sims = 1000
num_of_q = 400
```

#Creation of Dataframes
```{r}
quantiles <- data.frame("n10theta.05.1" = rep(0, num_of_q),
                        "n10theta.05.2" = rep(0, num_of_q),
                        "n10theta.05.3" = rep(0, num_of_q),
                        "n10theta.05.4" = rep(0, num_of_q),
                        "n10theta.05.5" = rep(0, num_of_q),
                        "n10theta.05.6" = rep(0, num_of_q),
                        "n10theta.05.7" = rep(0, num_of_q),
                        "n10theta.05.8" = rep(0, num_of_q),
                        "n10theta.05.9" = rep(0, num_of_q),
                        "n10theta.051" = rep(0, num_of_q),
                        "n10theta.1.1" = rep(0, num_of_q),
                        "n10theta.1.2" = rep(0, num_of_q),
                        "n10theta.1.3" = rep(0, num_of_q),
                        "n10theta.1.4" = rep(0, num_of_q),
                        "n10theta.1.5" = rep(0, num_of_q),
                        "n10theta.1.6" = rep(0, num_of_q),
                        "n10theta.1.7" = rep(0, num_of_q),
                        "n10theta.1.8" = rep(0, num_of_q),
                        "n10theta.1.9" = rep(0, num_of_q),
                        "n10theta.11" = rep(0, num_of_q),
                        "n10theta.15.1" = rep(0, num_of_q),
                        "n10theta.15.2" = rep(0, num_of_q),
                        "n10theta.15.3" = rep(0, num_of_q),
                        "n10theta.15.4" = rep(0, num_of_q),
                        "n10theta.15.5" = rep(0, num_of_q),
                        "n10theta.15.6" = rep(0, num_of_q),
                        "n10theta.15.7" = rep(0, num_of_q),
                        "n10theta.15.8" = rep(0, num_of_q),
                        "n10theta.15.9" = rep(0, num_of_q),
                        "n10theta.151" = rep(0, num_of_q),
                        "n10theta.2.1" = rep(0, num_of_q),
                        "n10theta.2.2" = rep(0, num_of_q),
                        "n10theta.2.3" = rep(0, num_of_q),
                        "n10theta.2.4" = rep(0, num_of_q),
                        "n10theta.2.5" = rep(0, num_of_q),
                        "n10theta.2.6" = rep(0, num_of_q),
                        "n10theta.2.7" = rep(0, num_of_q),
                        "n10theta.2.8" = rep(0, num_of_q),
                        "n10theta.2.9" = rep(0, num_of_q),
                        "n10theta.21" = rep(0, num_of_q),
                        "n10theta.25.1" = rep(0, num_of_q),
                        "n10theta.25.2" = rep(0, num_of_q),
                        "n10theta.25.3" = rep(0, num_of_q),
                        "n10theta.25.4" = rep(0, num_of_q),
                        "n10theta.25.5" = rep(0, num_of_q),
                        "n10theta.25.6" = rep(0, num_of_q),
                        "n10theta.25.7" = rep(0, num_of_q),
                        "n10theta.25.8" = rep(0, num_of_q),
                        "n10theta.25.9" = rep(0, num_of_q),
                        "n10theta.251" = rep(0, num_of_q),
                        "n10theta.3.1" = rep(0, num_of_q),
                        "n10theta.3.2" = rep(0, num_of_q),
                        "n10theta.3.3" = rep(0, num_of_q),
                        "n10theta.3.4" = rep(0, num_of_q),
                        "n10theta.3.5" = rep(0, num_of_q),
                        "n10theta.3.6" = rep(0, num_of_q),
                        "n10theta.3.7" = rep(0, num_of_q),
                        "n10theta.3.8" = rep(0, num_of_q),
                        "n10theta.3.9" = rep(0, num_of_q),
                        "n10theta.31" = rep(0, num_of_q),
                        "n10theta.35.1" = rep(0, num_of_q),
                        "n10theta.35.2" = rep(0, num_of_q),
                        "n10theta.35.3" = rep(0, num_of_q),
                        "n10theta.35.4" = rep(0, num_of_q),
                        "n10theta.35.5" = rep(0, num_of_q),
                        "n10theta.35.6" = rep(0, num_of_q),
                        "n10theta.35.7" = rep(0, num_of_q),
                        "n10theta.35.8" = rep(0, num_of_q),
                        "n10theta.35.9" = rep(0, num_of_q),
                        "n10theta.351" = rep(0, num_of_q),
                        "n10theta.4.1" = rep(0, num_of_q),
                        "n10theta.4.2" = rep(0, num_of_q),
                        "n10theta.4.3" = rep(0, num_of_q),
                        "n10theta.4.4" = rep(0, num_of_q),
                        "n10theta.4.5" = rep(0, num_of_q),
                        "n10theta.4.6" = rep(0, num_of_q),
                        "n10theta.4.7" = rep(0, num_of_q),
                        "n10theta.4.8" = rep(0, num_of_q),
                        "n10theta.4.9" = rep(0, num_of_q),
                        "n10theta.41" = rep(0, num_of_q),
                        "n15theta.05.1" = rep(0, num_of_q),
                        "n15theta.05.2" = rep(0, num_of_q),
                        "n15theta.05.3" = rep(0, num_of_q),
                        "n15theta.05.4" = rep(0, num_of_q),
                        "n15theta.05.5" = rep(0, num_of_q),
                        "n15theta.05.6" = rep(0, num_of_q),
                        "n15theta.05.7" = rep(0, num_of_q),
                        "n15theta.05.8" = rep(0, num_of_q),
                        "n15theta.05.9" = rep(0, num_of_q),
                        "n15theta.051" = rep(0, num_of_q),
                        "n15theta.1.1" = rep(0, num_of_q),
                        "n15theta.1.2" = rep(0, num_of_q),
                        "n15theta.1.3" = rep(0, num_of_q),
                        "n15theta.1.4" = rep(0, num_of_q),
                        "n15theta.1.5" = rep(0, num_of_q),
                        "n15theta.1.6" = rep(0, num_of_q),
                        "n15theta.1.7" = rep(0, num_of_q),
                        "n15theta.1.8" = rep(0, num_of_q),
                        "n15theta.1.9" = rep(0, num_of_q),
                        "n15theta.11" = rep(0, num_of_q),
                        "n15theta.15.1" = rep(0, num_of_q),
                        "n15theta.15.2" = rep(0, num_of_q),
                        "n15theta.15.3" = rep(0, num_of_q),
                        "n15theta.15.4" = rep(0, num_of_q),
                        "n15theta.15.5" = rep(0, num_of_q),
                        "n15theta.15.6" = rep(0, num_of_q),
                        "n15theta.15.7" = rep(0, num_of_q),
                        "n15theta.15.8" = rep(0, num_of_q),
                        "n15theta.15.9" = rep(0, num_of_q),
                        "n15theta.151" = rep(0, num_of_q),
                        "n15theta.2.1" = rep(0, num_of_q),
                        "n15theta.2.2" = rep(0, num_of_q),
                        "n15theta.2.3" = rep(0, num_of_q),
                        "n15theta.2.4" = rep(0, num_of_q),
                        "n15theta.2.5" = rep(0, num_of_q),
                        "n15theta.2.6" = rep(0, num_of_q),
                        "n15theta.2.7" = rep(0, num_of_q),
                        "n15theta.2.8" = rep(0, num_of_q),
                        "n15theta.2.9" = rep(0, num_of_q),
                        "n15theta.21" = rep(0, num_of_q),
                        "n15theta.25.1" = rep(0, num_of_q),
                        "n15theta.25.2" = rep(0, num_of_q),
                        "n15theta.25.3" = rep(0, num_of_q),
                        "n15theta.25.4" = rep(0, num_of_q),
                        "n15theta.25.5" = rep(0, num_of_q),
                        "n15theta.25.6" = rep(0, num_of_q),
                        "n15theta.25.7" = rep(0, num_of_q),
                        "n15theta.25.8" = rep(0, num_of_q),
                        "n15theta.25.9" = rep(0, num_of_q),
                        "n15theta.251" = rep(0, num_of_q),
                        "n15theta.3.1" = rep(0, num_of_q),
                        "n15theta.3.2" = rep(0, num_of_q),
                        "n15theta.3.3" = rep(0, num_of_q),
                        "n15theta.3.4" = rep(0, num_of_q),
                        "n15theta.3.5" = rep(0, num_of_q),
                        "n15theta.3.6" = rep(0, num_of_q),
                        "n15theta.3.7" = rep(0, num_of_q),
                        "n15theta.3.8" = rep(0, num_of_q),
                        "n15theta.3.9" = rep(0, num_of_q),
                        "n15theta.31" = rep(0, num_of_q),
                        "n15theta.35.1" = rep(0, num_of_q),
                        "n15theta.35.2" = rep(0, num_of_q),
                        "n15theta.35.3" = rep(0, num_of_q),
                        "n15theta.35.4" = rep(0, num_of_q),
                        "n15theta.35.5" = rep(0, num_of_q),
                        "n15theta.35.6" = rep(0, num_of_q),
                        "n15theta.35.7" = rep(0, num_of_q),
                        "n15theta.35.8" = rep(0, num_of_q),
                        "n15theta.35.9" = rep(0, num_of_q),
                        "n15theta.351" = rep(0, num_of_q),
                        "n15theta.4.1" = rep(0, num_of_q),
                        "n15theta.4.2" = rep(0, num_of_q),
                        "n15theta.4.3" = rep(0, num_of_q),
                        "n15theta.4.4" = rep(0, num_of_q),
                        "n15theta.4.5" = rep(0, num_of_q),
                        "n15theta.4.6" = rep(0, num_of_q),
                        "n15theta.4.7" = rep(0, num_of_q),
                        "n15theta.4.8" = rep(0, num_of_q),
                        "n15theta.4.9" = rep(0, num_of_q),
                        "n15theta.41" = rep(0, num_of_q),
                        "n20theta.05.1" = rep(0, num_of_q),
                        "n20theta.05.2" = rep(0, num_of_q),
                        "n20theta.05.3" = rep(0, num_of_q),
                        "n20theta.05.4" = rep(0, num_of_q),
                        "n20theta.05.5" = rep(0, num_of_q),
                        "n20theta.05.6" = rep(0, num_of_q),
                        "n20theta.05.7" = rep(0, num_of_q),
                        "n20theta.05.8" = rep(0, num_of_q),
                        "n20theta.05.9" = rep(0, num_of_q),
                        "n20theta.051" = rep(0, num_of_q),
                        "n20theta.1.1" = rep(0, num_of_q),
                        "n20theta.1.2" = rep(0, num_of_q),
                        "n20theta.1.3" = rep(0, num_of_q),
                        "n20theta.1.4" = rep(0, num_of_q),
                        "n20theta.1.5" = rep(0, num_of_q),
                        "n20theta.1.6" = rep(0, num_of_q),
                        "n20theta.1.7" = rep(0, num_of_q),
                        "n20theta.1.8" = rep(0, num_of_q),
                        "n20theta.1.9" = rep(0, num_of_q),
                        "n20theta.11" = rep(0, num_of_q),
                        "n20theta.15.1" = rep(0, num_of_q),
                        "n20theta.15.2" = rep(0, num_of_q),
                        "n20theta.15.3" = rep(0, num_of_q),
                        "n20theta.15.4" = rep(0, num_of_q),
                        "n20theta.15.5" = rep(0, num_of_q),
                        "n20theta.15.6" = rep(0, num_of_q),
                        "n20theta.15.7" = rep(0, num_of_q),
                        "n20theta.15.8" = rep(0, num_of_q),
                        "n20theta.15.9" = rep(0, num_of_q),
                        "n20theta.151" = rep(0, num_of_q),
                        "n20theta.2.1" = rep(0, num_of_q),
                        "n20theta.2.2" = rep(0, num_of_q),
                        "n20theta.2.3" = rep(0, num_of_q),
                        "n20theta.2.4" = rep(0, num_of_q),
                        "n20theta.2.5" = rep(0, num_of_q),
                        "n20theta.2.6" = rep(0, num_of_q),
                        "n20theta.2.7" = rep(0, num_of_q),
                        "n20theta.2.8" = rep(0, num_of_q),
                        "n20theta.2.9" = rep(0, num_of_q),
                        "n20theta.21" = rep(0, num_of_q),
                        "n20theta.25.1" = rep(0, num_of_q),
                        "n20theta.25.2" = rep(0, num_of_q),
                        "n20theta.25.3" = rep(0, num_of_q),
                        "n20theta.25.4" = rep(0, num_of_q),
                        "n20theta.25.5" = rep(0, num_of_q),
                        "n20theta.25.6" = rep(0, num_of_q),
                        "n20theta.25.7" = rep(0, num_of_q),
                        "n20theta.25.8" = rep(0, num_of_q),
                        "n20theta.25.9" = rep(0, num_of_q),
                        "n20theta.251" = rep(0, num_of_q),
                        "n20theta.3.1" = rep(0, num_of_q),
                        "n20theta.3.2" = rep(0, num_of_q),
                        "n20theta.3.3" = rep(0, num_of_q),
                        "n20theta.3.4" = rep(0, num_of_q),
                        "n20theta.3.5" = rep(0, num_of_q),
                        "n20theta.3.6" = rep(0, num_of_q),
                        "n20theta.3.7" = rep(0, num_of_q),
                        "n20theta.3.8" = rep(0, num_of_q),
                        "n20theta.3.9" = rep(0, num_of_q),
                        "n20theta.31" = rep(0, num_of_q),
                        "n20theta.35.1" = rep(0, num_of_q),
                        "n20theta.35.2" = rep(0, num_of_q),
                        "n20theta.35.3" = rep(0, num_of_q),
                        "n20theta.35.4" = rep(0, num_of_q),
                        "n20theta.35.5" = rep(0, num_of_q),
                        "n20theta.35.6" = rep(0, num_of_q),
                        "n20theta.35.7" = rep(0, num_of_q),
                        "n20theta.35.8" = rep(0, num_of_q),
                        "n20theta.35.9" = rep(0, num_of_q),
                        "n20theta.351" = rep(0, num_of_q),
                        "n20theta.4.1" = rep(0, num_of_q),
                        "n20theta.4.2" = rep(0, num_of_q),
                        "n20theta.4.3" = rep(0, num_of_q),
                        "n20theta.4.4" = rep(0, num_of_q),
                        "n20theta.4.5" = rep(0, num_of_q),
                        "n20theta.4.6" = rep(0, num_of_q),
                        "n20theta.4.7" = rep(0, num_of_q),
                        "n20theta.4.8" = rep(0, num_of_q),
                        "n20theta.4.9" = rep(0, num_of_q),
                        "n20theta.41" = rep(0, num_of_q),
                        "n25theta.05.1" = rep(0, num_of_q),
                        "n25theta.05.2" = rep(0, num_of_q),
                        "n25theta.05.3" = rep(0, num_of_q),
                        "n25theta.05.4" = rep(0, num_of_q),
                        "n25theta.05.5" = rep(0, num_of_q),
                        "n25theta.05.6" = rep(0, num_of_q),
                        "n25theta.05.7" = rep(0, num_of_q),
                        "n25theta.05.8" = rep(0, num_of_q),
                        "n25theta.05.9" = rep(0, num_of_q),
                        "n25theta.051" = rep(0, num_of_q),
                        "n25theta.1.1" = rep(0, num_of_q),
                        "n25theta.1.2" = rep(0, num_of_q),
                        "n25theta.1.3" = rep(0, num_of_q),
                        "n25theta.1.4" = rep(0, num_of_q),
                        "n25theta.1.5" = rep(0, num_of_q),
                        "n25theta.1.6" = rep(0, num_of_q),
                        "n25theta.1.7" = rep(0, num_of_q),
                        "n25theta.1.8" = rep(0, num_of_q),
                        "n25theta.1.9" = rep(0, num_of_q),
                        "n25theta.11" = rep(0, num_of_q),
                        "n25theta.15.1" = rep(0, num_of_q),
                        "n25theta.15.2" = rep(0, num_of_q),
                        "n25theta.15.3" = rep(0, num_of_q),
                        "n25theta.15.4" = rep(0, num_of_q),
                        "n25theta.15.5" = rep(0, num_of_q),
                        "n25theta.15.6" = rep(0, num_of_q),
                        "n25theta.15.7" = rep(0, num_of_q),
                        "n25theta.15.8" = rep(0, num_of_q),
                        "n25theta.15.9" = rep(0, num_of_q),
                        "n25theta.151" = rep(0, num_of_q),
                        "n25theta.2.1" = rep(0, num_of_q),
                        "n25theta.2.2" = rep(0, num_of_q),
                        "n25theta.2.3" = rep(0, num_of_q),
                        "n25theta.2.4" = rep(0, num_of_q),
                        "n25theta.2.5" = rep(0, num_of_q),
                        "n25theta.2.6" = rep(0, num_of_q),
                        "n25theta.2.7" = rep(0, num_of_q),
                        "n25theta.2.8" = rep(0, num_of_q),
                        "n25theta.2.9" = rep(0, num_of_q),
                        "n25theta.21" = rep(0, num_of_q),
                        "n25theta.25.1" = rep(0, num_of_q),
                        "n25theta.25.2" = rep(0, num_of_q),
                        "n25theta.25.3" = rep(0, num_of_q),
                        "n25theta.25.4" = rep(0, num_of_q),
                        "n25theta.25.5" = rep(0, num_of_q),
                        "n25theta.25.6" = rep(0, num_of_q),
                        "n25theta.25.7" = rep(0, num_of_q),
                        "n25theta.25.8" = rep(0, num_of_q),
                        "n25theta.25.9" = rep(0, num_of_q),
                        "n25theta.251" = rep(0, num_of_q),
                        "n25theta.3.1" = rep(0, num_of_q),
                        "n25theta.3.2" = rep(0, num_of_q),
                        "n25theta.3.3" = rep(0, num_of_q),
                        "n25theta.3.4" = rep(0, num_of_q),
                        "n25theta.3.5" = rep(0, num_of_q),
                        "n25theta.3.6" = rep(0, num_of_q),
                        "n25theta.3.7" = rep(0, num_of_q),
                        "n25theta.3.8" = rep(0, num_of_q),
                        "n25theta.3.9" = rep(0, num_of_q),
                        "n25theta.31" = rep(0, num_of_q),
                        "n25theta.35.1" = rep(0, num_of_q),
                        "n25theta.35.2" = rep(0, num_of_q),
                        "n25theta.35.3" = rep(0, num_of_q),
                        "n25theta.35.4" = rep(0, num_of_q),
                        "n25theta.35.5" = rep(0, num_of_q),
                        "n25theta.35.6" = rep(0, num_of_q),
                        "n25theta.35.7" = rep(0, num_of_q),
                        "n25theta.35.8" = rep(0, num_of_q),
                        "n25theta.35.9" = rep(0, num_of_q),
                        "n25theta.351" = rep(0, num_of_q),
                        "n25theta.4.1" = rep(0, num_of_q),
                        "n25theta.4.2" = rep(0, num_of_q),
                        "n25theta.4.3" = rep(0, num_of_q),
                        "n25theta.4.4" = rep(0, num_of_q),
                        "n25theta.4.5" = rep(0, num_of_q),
                        "n25theta.4.6" = rep(0, num_of_q),
                        "n25theta.4.7" = rep(0, num_of_q),
                        "n25theta.4.8" = rep(0, num_of_q),
                        "n25theta.4.9" = rep(0, num_of_q),
                        "n25theta.41" = rep(0, num_of_q),
                        "n30theta.05.1" = rep(0, num_of_q),
                        "n30theta.05.2" = rep(0, num_of_q),
                        "n30theta.05.3" = rep(0, num_of_q),
                        "n30theta.05.4" = rep(0, num_of_q),
                        "n30theta.05.5" = rep(0, num_of_q),
                        "n30theta.05.6" = rep(0, num_of_q),
                        "n30theta.05.7" = rep(0, num_of_q),
                        "n30theta.05.8" = rep(0, num_of_q),
                        "n30theta.05.9" = rep(0, num_of_q),
                        "n30theta.051" = rep(0, num_of_q),
                        "n30theta.1.1" = rep(0, num_of_q),
                        "n30theta.1.2" = rep(0, num_of_q),
                        "n30theta.1.3" = rep(0, num_of_q),
                        "n30theta.1.4" = rep(0, num_of_q),
                        "n30theta.1.5" = rep(0, num_of_q),
                        "n30theta.1.6" = rep(0, num_of_q),
                        "n30theta.1.7" = rep(0, num_of_q),
                        "n30theta.1.8" = rep(0, num_of_q),
                        "n30theta.1.9" = rep(0, num_of_q),
                        "n30theta.11" = rep(0, num_of_q),
                        "n30theta.15.1" = rep(0, num_of_q),
                        "n30theta.15.2" = rep(0, num_of_q),
                        "n30theta.15.3" = rep(0, num_of_q),
                        "n30theta.15.4" = rep(0, num_of_q),
                        "n30theta.15.5" = rep(0, num_of_q),
                        "n30theta.15.6" = rep(0, num_of_q),
                        "n30theta.15.7" = rep(0, num_of_q),
                        "n30theta.15.8" = rep(0, num_of_q),
                        "n30theta.15.9" = rep(0, num_of_q),
                        "n30theta.151" = rep(0, num_of_q),
                        "n30theta.2.1" = rep(0, num_of_q),
                        "n30theta.2.2" = rep(0, num_of_q),
                        "n30theta.2.3" = rep(0, num_of_q),
                        "n30theta.2.4" = rep(0, num_of_q),
                        "n30theta.2.5" = rep(0, num_of_q),
                        "n30theta.2.6" = rep(0, num_of_q),
                        "n30theta.2.7" = rep(0, num_of_q),
                        "n30theta.2.8" = rep(0, num_of_q),
                        "n30theta.2.9" = rep(0, num_of_q),
                        "n30theta.21" = rep(0, num_of_q),
                        "n30theta.25.1" = rep(0, num_of_q),
                        "n30theta.25.2" = rep(0, num_of_q),
                        "n30theta.25.3" = rep(0, num_of_q),
                        "n30theta.25.4" = rep(0, num_of_q),
                        "n30theta.25.5" = rep(0, num_of_q),
                        "n30theta.25.6" = rep(0, num_of_q),
                        "n30theta.25.7" = rep(0, num_of_q),
                        "n30theta.25.8" = rep(0, num_of_q),
                        "n30theta.25.9" = rep(0, num_of_q),
                        "n30theta.251" = rep(0, num_of_q),
                        "n30theta.3.1" = rep(0, num_of_q),
                        "n30theta.3.2" = rep(0, num_of_q),
                        "n30theta.3.3" = rep(0, num_of_q),
                        "n30theta.3.4" = rep(0, num_of_q),
                        "n30theta.3.5" = rep(0, num_of_q),
                        "n30theta.3.6" = rep(0, num_of_q),
                        "n30theta.3.7" = rep(0, num_of_q),
                        "n30theta.3.8" = rep(0, num_of_q),
                        "n30theta.3.9" = rep(0, num_of_q),
                        "n30theta.31" = rep(0, num_of_q),
                        "n30theta.35.1" = rep(0, num_of_q),
                        "n30theta.35.2" = rep(0, num_of_q),
                        "n30theta.35.3" = rep(0, num_of_q),
                        "n30theta.35.4" = rep(0, num_of_q),
                        "n30theta.35.5" = rep(0, num_of_q),
                        "n30theta.35.6" = rep(0, num_of_q),
                        "n30theta.35.7" = rep(0, num_of_q),
                        "n30theta.35.8" = rep(0, num_of_q),
                        "n30theta.35.9" = rep(0, num_of_q),
                        "n30theta.351" = rep(0, num_of_q),
                        "n30theta.4.1" = rep(0, num_of_q),
                        "n30theta.4.2" = rep(0, num_of_q),
                        "n30theta.4.3" = rep(0, num_of_q),
                        "n30theta.4.4" = rep(0, num_of_q),
                        "n30theta.4.5" = rep(0, num_of_q),
                        "n30theta.4.6" = rep(0, num_of_q),
                        "n30theta.4.7" = rep(0, num_of_q),
                        "n30theta.4.8" = rep(0, num_of_q),
                        "n30theta.4.9" = rep(0, num_of_q),
                        "n30theta.41" = rep(0, num_of_q),
                        "n35theta.05.1" = rep(0, num_of_q),
                        "n35theta.05.2" = rep(0, num_of_q),
                        "n35theta.05.3" = rep(0, num_of_q),
                        "n35theta.05.4" = rep(0, num_of_q),
                        "n35theta.05.5" = rep(0, num_of_q),
                        "n35theta.05.6" = rep(0, num_of_q),
                        "n35theta.05.7" = rep(0, num_of_q),
                        "n35theta.05.8" = rep(0, num_of_q),
                        "n35theta.05.9" = rep(0, num_of_q),
                        "n35theta.051" = rep(0, num_of_q),
                        "n35theta.1.1" = rep(0, num_of_q),
                        "n35theta.1.2" = rep(0, num_of_q),
                        "n35theta.1.3" = rep(0, num_of_q),
                        "n35theta.1.4" = rep(0, num_of_q),
                        "n35theta.1.5" = rep(0, num_of_q),
                        "n35theta.1.6" = rep(0, num_of_q),
                        "n35theta.1.7" = rep(0, num_of_q),
                        "n35theta.1.8" = rep(0, num_of_q),
                        "n35theta.1.9" = rep(0, num_of_q),
                        "n35theta.11" = rep(0, num_of_q),
                        "n35theta.15.1" = rep(0, num_of_q),
                        "n35theta.15.2" = rep(0, num_of_q),
                        "n35theta.15.3" = rep(0, num_of_q),
                        "n35theta.15.4" = rep(0, num_of_q),
                        "n35theta.15.5" = rep(0, num_of_q),
                        "n35theta.15.6" = rep(0, num_of_q),
                        "n35theta.15.7" = rep(0, num_of_q),
                        "n35theta.15.8" = rep(0, num_of_q),
                        "n35theta.15.9" = rep(0, num_of_q),
                        "n35theta.151" = rep(0, num_of_q),
                        "n35theta.2.1" = rep(0, num_of_q),
                        "n35theta.2.2" = rep(0, num_of_q),
                        "n35theta.2.3" = rep(0, num_of_q),
                        "n35theta.2.4" = rep(0, num_of_q),
                        "n35theta.2.5" = rep(0, num_of_q),
                        "n35theta.2.6" = rep(0, num_of_q),
                        "n35theta.2.7" = rep(0, num_of_q),
                        "n35theta.2.8" = rep(0, num_of_q),
                        "n35theta.2.9" = rep(0, num_of_q),
                        "n35theta.21" = rep(0, num_of_q),
                        "n35theta.25.1" = rep(0, num_of_q),
                        "n35theta.25.2" = rep(0, num_of_q),
                        "n35theta.25.3" = rep(0, num_of_q),
                        "n35theta.25.4" = rep(0, num_of_q),
                        "n35theta.25.5" = rep(0, num_of_q),
                        "n35theta.25.6" = rep(0, num_of_q),
                        "n35theta.25.7" = rep(0, num_of_q),
                        "n35theta.25.8" = rep(0, num_of_q),
                        "n35theta.25.9" = rep(0, num_of_q),
                        "n35theta.251" = rep(0, num_of_q),
                        "n35theta.3.1" = rep(0, num_of_q),
                        "n35theta.3.2" = rep(0, num_of_q),
                        "n35theta.3.3" = rep(0, num_of_q),
                        "n35theta.3.4" = rep(0, num_of_q),
                        "n35theta.3.5" = rep(0, num_of_q),
                        "n35theta.3.6" = rep(0, num_of_q),
                        "n35theta.3.7" = rep(0, num_of_q),
                        "n35theta.3.8" = rep(0, num_of_q),
                        "n35theta.3.9" = rep(0, num_of_q),
                        "n35theta.31" = rep(0, num_of_q),
                        "n35theta.35.1" = rep(0, num_of_q),
                        "n35theta.35.2" = rep(0, num_of_q),
                        "n35theta.35.3" = rep(0, num_of_q),
                        "n35theta.35.4" = rep(0, num_of_q),
                        "n35theta.35.5" = rep(0, num_of_q),
                        "n35theta.35.6" = rep(0, num_of_q),
                        "n35theta.35.7" = rep(0, num_of_q),
                        "n35theta.35.8" = rep(0, num_of_q),
                        "n35theta.35.9" = rep(0, num_of_q),
                        "n35theta.351" = rep(0, num_of_q),
                        "n35theta.4.1" = rep(0, num_of_q),
                        "n35theta.4.2" = rep(0, num_of_q),
                        "n35theta.4.3" = rep(0, num_of_q),
                        "n35theta.4.4" = rep(0, num_of_q),
                        "n35theta.4.5" = rep(0, num_of_q),
                        "n35theta.4.6" = rep(0, num_of_q),
                        "n35theta.4.7" = rep(0, num_of_q),
                        "n35theta.4.8" = rep(0, num_of_q),
                        "n35theta.4.9" = rep(0, num_of_q),
                        "n35theta.41" = rep(0, num_of_q),
                        "n40theta.05.1" = rep(0, num_of_q),
                        "n40theta.05.2" = rep(0, num_of_q),
                        "n40theta.05.3" = rep(0, num_of_q),
                        "n40theta.05.4" = rep(0, num_of_q),
                        "n40theta.05.5" = rep(0, num_of_q),
                        "n40theta.05.6" = rep(0, num_of_q),
                        "n40theta.05.7" = rep(0, num_of_q),
                        "n40theta.05.8" = rep(0, num_of_q),
                        "n40theta.05.9" = rep(0, num_of_q),
                        "n40theta.051" = rep(0, num_of_q),
                        "n40theta.1.1" = rep(0, num_of_q),
                        "n40theta.1.2" = rep(0, num_of_q),
                        "n40theta.1.3" = rep(0, num_of_q),
                        "n40theta.1.4" = rep(0, num_of_q),
                        "n40theta.1.5" = rep(0, num_of_q),
                        "n40theta.1.6" = rep(0, num_of_q),
                        "n40theta.1.7" = rep(0, num_of_q),
                        "n40theta.1.8" = rep(0, num_of_q),
                        "n40theta.1.9" = rep(0, num_of_q),
                        "n40theta.11" = rep(0, num_of_q),
                        "n40theta.15.1" = rep(0, num_of_q),
                        "n40theta.15.2" = rep(0, num_of_q),
                        "n40theta.15.3" = rep(0, num_of_q),
                        "n40theta.15.4" = rep(0, num_of_q),
                        "n40theta.15.5" = rep(0, num_of_q),
                        "n40theta.15.6" = rep(0, num_of_q),
                        "n40theta.15.7" = rep(0, num_of_q),
                        "n40theta.15.8" = rep(0, num_of_q),
                        "n40theta.15.9" = rep(0, num_of_q),
                        "n40theta.151" = rep(0, num_of_q),
                        "n40theta.2.1" = rep(0, num_of_q),
                        "n40theta.2.2" = rep(0, num_of_q),
                        "n40theta.2.3" = rep(0, num_of_q),
                        "n40theta.2.4" = rep(0, num_of_q),
                        "n40theta.2.5" = rep(0, num_of_q),
                        "n40theta.2.6" = rep(0, num_of_q),
                        "n40theta.2.7" = rep(0, num_of_q),
                        "n40theta.2.8" = rep(0, num_of_q),
                        "n40theta.2.9" = rep(0, num_of_q),
                        "n40theta.21" = rep(0, num_of_q),
                        "n40theta.25.1" = rep(0, num_of_q),
                        "n40theta.25.2" = rep(0, num_of_q),
                        "n40theta.25.3" = rep(0, num_of_q),
                        "n40theta.25.4" = rep(0, num_of_q),
                        "n40theta.25.5" = rep(0, num_of_q),
                        "n40theta.25.6" = rep(0, num_of_q),
                        "n40theta.25.7" = rep(0, num_of_q),
                        "n40theta.25.8" = rep(0, num_of_q),
                        "n40theta.25.9" = rep(0, num_of_q),
                        "n40theta.251" = rep(0, num_of_q),
                        "n40theta.3.1" = rep(0, num_of_q),
                        "n40theta.3.2" = rep(0, num_of_q),
                        "n40theta.3.3" = rep(0, num_of_q),
                        "n40theta.3.4" = rep(0, num_of_q),
                        "n40theta.3.5" = rep(0, num_of_q),
                        "n40theta.3.6" = rep(0, num_of_q),
                        "n40theta.3.7" = rep(0, num_of_q),
                        "n40theta.3.8" = rep(0, num_of_q),
                        "n40theta.3.9" = rep(0, num_of_q),
                        "n40theta.31" = rep(0, num_of_q),
                        "n40theta.35.1" = rep(0, num_of_q),
                        "n40theta.35.2" = rep(0, num_of_q),
                        "n40theta.35.3" = rep(0, num_of_q),
                        "n40theta.35.4" = rep(0, num_of_q),
                        "n40theta.35.5" = rep(0, num_of_q),
                        "n40theta.35.6" = rep(0, num_of_q),
                        "n40theta.35.7" = rep(0, num_of_q),
                        "n40theta.35.8" = rep(0, num_of_q),
                        "n40theta.35.9" = rep(0, num_of_q),
                        "n40theta.351" = rep(0, num_of_q),
                        "n40theta.4.1" = rep(0, num_of_q),
                        "n40theta.4.2" = rep(0, num_of_q),
                        "n40theta.4.3" = rep(0, num_of_q),
                        "n40theta.4.4" = rep(0, num_of_q),
                        "n40theta.4.5" = rep(0, num_of_q),
                        "n40theta.4.6" = rep(0, num_of_q),
                        "n40theta.4.7" = rep(0, num_of_q),
                        "n40theta.4.8" = rep(0, num_of_q),
                        "n40theta.4.9" = rep(0, num_of_q),
                        "n40theta.41" = rep(0, num_of_q))
                        
mat_nt <- matrix(NA, ncol = 56, nrow = num_of_sims)
df_nt <- as.data.frame(mat_nt)
df_nt <- df_nt %>%
  select(V1 : V56)
names(df_nt)[1]<- "n10theta.05"
names(df_nt)[2]<- "n10theta.1"
names(df_nt)[3]<- "n10theta.15"
names(df_nt)[4]<- "n10theta.2"
names(df_nt)[5]<- "n10theta.25"
names(df_nt)[6]<- "n10theta.3"
names(df_nt)[7]<- "n10theta.35"
names(df_nt)[8]<- "n10theta.4"
names(df_nt)[9]<- "n20theta.05"
names(df_nt)[10]<- "n20theta.1"
names(df_nt)[11]<- "n20theta.15"
names(df_nt)[12]<- "n20theta.2"
names(df_nt)[13]<- "n20theta.25"
names(df_nt)[14]<- "n20theta.3"
names(df_nt)[15]<- "n20theta.35"
names(df_nt)[16]<- "n20theta.4"
names(df_nt)[17]<- "n30theta.05"
names(df_nt)[18]<- "n30theta.1"
names(df_nt)[19]<- "n30theta.15"
names(df_nt)[20]<- "n30theta.2"
names(df_nt)[21]<- "n30theta.25"
names(df_nt)[22]<- "n30theta.3"
names(df_nt)[23]<- "n30theta.35"
names(df_nt)[24]<- "n30theta.4"
names(df_nt)[25]<- "n15theta.05"
names(df_nt)[26]<- "n15theta.1"
names(df_nt)[27]<- "n15theta.15"
names(df_nt)[28]<- "n15theta.2"
names(df_nt)[29]<- "n15theta.25"
names(df_nt)[30]<- "n15theta.3"
names(df_nt)[31]<- "n15theta.35"
names(df_nt)[32]<- "n15theta.4"
names(df_nt)[33]<- "n25theta.05"
names(df_nt)[34]<- "n25theta.1"
names(df_nt)[35]<- "n25theta.15"
names(df_nt)[36]<- "n25theta.2"
names(df_nt)[37]<- "n25theta.25"
names(df_nt)[38]<- "n25theta.3"
names(df_nt)[39]<- "n25theta.35"
names(df_nt)[40]<- "n25theta.4"
names(df_nt)[41]<- "n35theta.05"
names(df_nt)[42]<- "n35theta.1"
names(df_nt)[43]<- "n35theta.15"
names(df_nt)[44]<- "n35theta.2"
names(df_nt)[45]<- "n35theta.25"
names(df_nt)[46]<- "n35theta.3"
names(df_nt)[47]<- "n35theta.35"
names(df_nt)[48]<- "n35theta.4"
names(df_nt)[49]<- "n40theta.05"
names(df_nt)[50]<- "n40theta.1"
names(df_nt)[51]<- "n40theta.15"
names(df_nt)[52]<- "n40theta.2"
names(df_nt)[53]<- "n40theta.25"
names(df_nt)[54]<- "n40theta.3"
names(df_nt)[55]<- "n40theta.35"
names(df_nt)[56]<- "n40theta.4"
```

```{r}
b10.05.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .05])
b10.05.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .05])
b10.05.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .05])
b10.05.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .05])
b10.05.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .05])
b10.05.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .05])
b10.05.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .05])
b10.05.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .05])
b10.05.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .05])

b10.1.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .1])
b10.1.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .1])
b10.1.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .1])
b10.1.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .1])
b10.1.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .1])
b10.1.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .1])
b10.1.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .1])
b10.1.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .1])
b10.1.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .1])

b10.15.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .15])
b10.15.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .15])
b10.15.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .15])
b10.15.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .15])
b10.15.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .15])
b10.15.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .15])
b10.15.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .15])
b10.15.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .15])
b10.15.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .15])

b10.2.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .2])
b10.2.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .2])
b10.2.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .2])
b10.2.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .2])
b10.2.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .2])
b10.2.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .2])
b10.2.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .2])
b10.2.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .2])
b10.2.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .2])

b10.25.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .25])
b10.25.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .25])
b10.25.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .25])
b10.25.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .25])
b10.25.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .25])
b10.25.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .25])
b10.25.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .25])
b10.25.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .25])
b10.25.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .25])

b10.3.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .3])
b10.3.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .3])
b10.3.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .3])
b10.3.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .3])
b10.3.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .3])
b10.3.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .3])
b10.3.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .3])
b10.3.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .3])
b10.3.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .3])

b10.35.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .35])
b10.35.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .35])
b10.35.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .35])
b10.35.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .35])
b10.35.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .35])
b10.35.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .35])
b10.35.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .35])
b10.35.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .35])
b10.35.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .35])

b10.4.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .4])
b10.4.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .4])
b10.4.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .4])
b10.4.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .4])
b10.4.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .4])
b10.4.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .4])
b10.4.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .4])
b10.4.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .4])
b10.4.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 10 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 10 & df.Rho$Theta == .4])

b15.05.1 = qbeta(.1, .1, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .05])
b15.05.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .05])
b15.05.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .05])
b15.05.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .05])
b15.05.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .05])
b15.05.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .05])
b15.05.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .05])
b15.05.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .05])
b15.05.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .05])

b15.1.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .1])
b15.1.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .1])
b15.1.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .1])
b15.1.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .1])
b15.1.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .1])
b15.1.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .1])
b15.1.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .1])
b15.1.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .1])
b15.1.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .1])

b15.15.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .15])
b15.15.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .15])
b15.15.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .15])
b15.15.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .15])
b15.15.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .15])
b15.15.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .15])
b15.15.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .15])
b15.15.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .15])
b15.15.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .15])

b15.2.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .2])
b15.2.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .2])
b15.2.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .2])
b15.2.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .2])
b15.2.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .2])
b15.2.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .2])
b15.2.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .2])
b15.2.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .2])
b15.2.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .2])

b15.25.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .25])
b15.25.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .25])
b15.25.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .25])
b15.25.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .25])
b15.25.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .25])
b15.25.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .25])
b15.25.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .25])
b15.25.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .25])
b15.25.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .25])

b15.3.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .3])
b15.3.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .3])
b15.3.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .3])
b15.3.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .3])
b15.3.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .3])
b15.3.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .3])
b15.3.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .3])
b15.3.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .3])
b15.3.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .3])

b15.35.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .35])
b15.35.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .35])
b15.35.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .35])
b15.35.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .35])
b15.35.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .35])
b15.35.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .35])
b15.35.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .35])
b15.35.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .35])
b15.35.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .35])

b15.4.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .4])
b15.4.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .4])
b15.4.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .4])
b15.4.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .4])
b15.4.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .4])
b15.4.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .4])
b15.4.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .4])
b15.4.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .4])
b15.4.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 15 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 15 & df.Rho$Theta == .4])

b20.05.1 = qbeta(.1, .1, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .05])
b20.05.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .05])
b20.05.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .05])
b20.05.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .05])
b20.05.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .05])
b20.05.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .05])
b20.05.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .05])
b20.05.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .05])
b20.05.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .05])

b20.1.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .1])
b20.1.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .1])
b20.1.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .1])
b20.1.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .1])
b20.1.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .1])
b20.1.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .1])
b20.1.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .1])
b20.1.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .1])
b20.1.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .1])

b20.15.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .15])
b20.15.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .15])
b20.15.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .15])
b20.15.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .15])
b20.15.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .15])
b20.15.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .15])
b20.15.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .15])
b20.15.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .15])
b20.15.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .15])

b20.2.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .2])
b20.2.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .2])
b20.2.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .2])
b20.2.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .2])
b20.2.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .2])
b20.2.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .2])
b20.2.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .2])
b20.2.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .2])
b20.2.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .2])

b20.25.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .25])
b20.25.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .25])
b20.25.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .25])
b20.25.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .25])
b20.25.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .25])
b20.25.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .25])
b20.25.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .25])
b20.25.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .25])
b20.25.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .25])

b20.3.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .3])
b20.3.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .3])
b20.3.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .3])
b20.3.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .3])
b20.3.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .3])
b20.3.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .3])
b20.3.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .3])
b20.3.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .3])
b20.3.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .3])

b20.35.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .35])
b20.35.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .35])
b20.35.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .35])
b20.35.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .35])
b20.35.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .35])
b20.35.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .35])
b20.35.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .35])
b20.35.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .35])
b20.35.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .35])

b20.4.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .4])
b20.4.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .4])
b20.4.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .4])
b20.4.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .4])
b20.4.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .4])
b20.4.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .4])
b20.4.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .4])
b20.4.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .4])
b20.4.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 20 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 20 & df.Rho$Theta == .4])

b25.05.1 = qbeta(.1, .1, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .05])
b25.05.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .05])
b25.05.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .05])
b25.05.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .05])
b25.05.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .05])
b25.05.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .05])
b25.05.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .05])
b25.05.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .05])
b25.05.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .05])

b25.1.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .1])
b25.1.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .1])
b25.1.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .1])
b25.1.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .1])
b25.1.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .1])
b25.1.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .1])
b25.1.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .1])
b25.1.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .1])
b25.1.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .1])

b25.15.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .15])
b25.15.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .15])
b25.15.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .15])
b25.15.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .15])
b25.15.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .15])
b25.15.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .15])
b25.15.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .15])
b25.15.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .15])
b25.15.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .15])

b25.2.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .2])
b25.2.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .2])
b25.2.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .2])
b25.2.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .2])
b25.2.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .2])
b25.2.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .2])
b25.2.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .2])
b25.2.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .2])
b25.2.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .2])

b25.25.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .25])
b25.25.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .25])
b25.25.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .25])
b25.25.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .25])
b25.25.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .25])
b25.25.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .25])
b25.25.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .25])
b25.25.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .25])
b25.25.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .25])

b25.3.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .3])
b25.3.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .3])
b25.3.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .3])
b25.3.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .3])
b25.3.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .3])
b25.3.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .3])
b25.3.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .3])
b25.3.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .3])
b25.3.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .3])

b25.35.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .35])
b25.35.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .35])
b25.35.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .35])
b25.35.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .35])
b25.35.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .35])
b25.35.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .35])
b25.35.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .35])
b25.35.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .35])
b25.35.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .35])

b25.4.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .4])
b25.4.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .4])
b25.4.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .4])
b25.4.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .4])
b25.4.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .4])
b25.4.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .4])
b25.4.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .4])
b25.4.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .4])
b25.4.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 25 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 25 & df.Rho$Theta == .4])

b30.05.1 = qbeta(.1, .1, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .05])
b30.05.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .05])
b30.05.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .05])
b30.05.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .05])
b30.05.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .05])
b30.05.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .05])
b30.05.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .05])
b30.05.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .05])
b30.05.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .05])

b30.1.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .1])
b30.1.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .1])
b30.1.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .1])
b30.1.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .1])
b30.1.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .1])
b30.1.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .1])
b30.1.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .1])
b30.1.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .1])
b30.1.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .1])

b30.15.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .15])
b30.15.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .15])
b30.15.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .15])
b30.15.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .15])
b30.15.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .15])
b30.15.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .15])
b30.15.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .15])
b30.15.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .15])
b30.15.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .15])

b30.2.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .2])
b30.2.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .2])
b30.2.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .2])
b30.2.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .2])
b30.2.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .2])
b30.2.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .2])
b30.2.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .2])
b30.2.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .2])
b30.2.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .2])

b30.25.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .25])
b30.25.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .25])
b30.25.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .25])
b30.25.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .25])
b30.25.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .25])
b30.25.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .25])
b30.25.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .25])
b30.25.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .25])
b30.25.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .25])

b30.3.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .3])
b30.3.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .3])
b30.3.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .3])
b30.3.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .3])
b30.3.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .3])
b30.3.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .3])
b30.3.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .3])
b30.3.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .3])
b30.3.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .3])

b30.35.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .35])
b30.35.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .35])
b30.35.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .35])
b30.35.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .35])
b30.35.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .35])
b30.35.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .35])
b30.35.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .35])
b30.35.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .35])
b30.35.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .35])

b30.4.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .4])
b30.4.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .4])
b30.4.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .4])
b30.4.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .4])
b30.4.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .4])
b30.4.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .4])
b30.4.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .4])
b30.4.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .4])
b30.4.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 30 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 30 & df.Rho$Theta == .4])

b35.05.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .05])
b35.05.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .05])
b35.05.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .05])
b35.05.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .05])
b35.05.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .05])
b35.05.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .05])
b35.05.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .05])
b35.05.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .05])
b35.05.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .05])

b35.1.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .1])
b35.1.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .1])
b35.1.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .1])
b35.1.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .1])
b35.1.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .1])
b35.1.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .1])
b35.1.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .1])
b35.1.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .1])
b35.1.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .1])

b35.15.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .15])
b35.15.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .15])
b35.15.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .15])
b35.15.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .15])
b35.15.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .15])
b35.15.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .15])
b35.15.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .15])
b35.15.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .15])
b35.15.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .15])

b35.2.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .2])
b35.2.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .2])
b35.2.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .2])
b35.2.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .2])
b35.2.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .2])
b35.2.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .2])
b35.2.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .2])
b35.2.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .2])
b35.2.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .2])

b35.25.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .25])
b35.25.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .25])
b35.25.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .25])
b35.25.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .25])
b35.25.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .25])
b35.25.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .25])
b35.25.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .25])
b35.25.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .25])
b35.25.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .25])

b35.3.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .3])
b35.3.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .3])
b35.3.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .3])
b35.3.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .3])
b35.3.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .3])
b35.3.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .3])
b35.3.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .3])
b35.3.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .3])
b35.3.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .3])

b35.35.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .35])
b35.35.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .35])
b35.35.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .35])
b35.35.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .35])
b35.35.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .35])
b35.35.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .35])
b35.35.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .35])
b35.35.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .35])
b35.35.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .35])

b35.4.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .4])
b35.4.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .4])
b35.4.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .4])
b35.4.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .4])
b35.4.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .4])
b35.4.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .4])
b35.4.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .4])
b35.4.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .4])
b35.4.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 35 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 35 & df.Rho$Theta == .4])

b40.05.1 = qbeta(.1, .1, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .05])
b40.05.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .05])
b40.05.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .05])
b40.05.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .05])
b40.05.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .05])
b40.05.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .05])
b40.05.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .05])
b40.05.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .05])
b40.05.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .05], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .05])

b40.1.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .1])
b40.1.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .1])
b40.1.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .1])
b40.1.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .1])
b40.1.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .1])
b40.1.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .1])
b40.1.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .1])
b40.1.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .1])
b40.1.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .1], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .1])

b40.15.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .15])
b40.15.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .15])
b40.15.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .15])
b40.15.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .15])
b40.15.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .15])
b40.15.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .15])
b40.15.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .15])
b40.15.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .15])
b40.15.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .15], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .15])

b40.2.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .2])
b40.2.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .2])
b40.2.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .2])
b40.2.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .2])
b40.2.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .2])
b40.2.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .2])
b40.2.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .2])
b40.2.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .2])
b40.2.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .2], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .2])

b40.25.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .25])
b40.25.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .25])
b40.25.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .25])
b40.25.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .25])
b40.25.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .25])
b40.25.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .25])
b40.25.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .25])
b40.25.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .25])
b40.25.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .25], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .25])

b40.3.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .3])
b40.3.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .3])
b40.3.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .3])
b40.3.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .3])
b40.3.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .3])
b40.3.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .3])
b40.3.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .3])
b40.3.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .3])
b40.3.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .3], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .3])

b40.35.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .35])
b40.35.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .35])
b40.35.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .35])
b40.35.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .35])
b40.35.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .35])
b40.35.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .35])
b40.35.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .35])
b40.35.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .35])
b40.35.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .35], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .35])

b40.4.1 = qbeta(.1, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .4])
b40.4.2 = qbeta(.2, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .4])
b40.4.3 = qbeta(.3, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .4])
b40.4.4 = qbeta(.4, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .4])
b40.4.5 = qbeta(.5, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .4])
b40.4.6 = qbeta(.6, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .4])
b40.4.7 = qbeta(.7, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .4])
b40.4.8 = qbeta(.8, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .4])
b40.4.9 = qbeta(.9, df.Rho$fita[df.Rho$n == 40 & df.Rho$Theta == .4], df.Rho$fitb[df.Rho$n == 40 & df.Rho$Theta == .4])
```

#For loop
```{r}
for (h in 53:num_of_q) {
  for (i in 1:num_of_sims) {
#n = 10 theta = .05
x95 <- rnorm(10, mu, sd)
z95 <- rnorm(10, mu, sd)
xz95 <- cbind(x95, z95)
xz95 <- as.data.frame(xz95)
xz95$y95 <- rho * xz95$x95 + (1 - (rho)^2) * xz95$z95

xy95 <- xz95 %>%
  filter(x95 <= qnorm(.95))

r95 <- cor(xy95$x95, xy95$y95)
df_nt$n10theta.05[i] <- abs(r95)
  
#n = 10 theta = .1
x90 <- rnorm(10, mu, sd)
z90 <- rnorm(10, mu, sd)
xz90 <- cbind(x90, z90)
xz90 <- as.data.frame(xz90)
xz90$y90 <- rho * xz90$x90 + (1 - (rho)^2) * xz90$z90


xy90 <- xz90 %>%
  filter(x90 <= qnorm(.90))

r90 <- cor(xy90$x90, xy90$y90)
df_nt$n10theta.1[i] <- abs(r90)

#n = 10 theta = .15
x85 <- rnorm(10, mu, sd)
z85 <- rnorm(10, mu, sd)
xz85 <- cbind(x85, z85)
xz85 <- as.data.frame(xz85)
xz85$y85 <- rho * xz85$x85 + (1 - (rho)^2) * xz85$z85
  

xy85 <- xz85 %>%
  filter(x85 <= qnorm(.85))

r85 <- cor(xy85$x85, xy85$y85)
df_nt$n10theta.15[i] <- abs(r85)

#n = 10 theta = .2
x80 <- rnorm(10, mu, sd)
z80 <- rnorm(10, mu, sd)
xz80 <- cbind(x80, z80)
xz80 <- as.data.frame(xz80)
xz80$y80 <- rho * xz80$x80 + (1 - (rho)^2) * xz80$z80
  

xy80 <- xz80%>%
  filter(x80 <= qnorm(.8))

r80 <- cor(xy80$x80, xy80$y80)
df_nt$n10theta.2[i] <- abs(r80)

#n = 10 theta = .25
x75 <- rnorm(10, mu, sd)
z75 <- rnorm(10, mu, sd)
xz75 <- cbind(x75, z75)
xz75 <- as.data.frame(xz75)
xz75$y75 <- rho * xz75$x75 + (1 - (rho)^2) * xz75$z75
  

xy75 <- xz75 %>%
  filter(x75 <= qnorm(.75))

r75 <- cor(xy75$x75, xy75$y75)
df_nt$n10theta.25[i] <- abs(r75)

#n = 10 theta = .3
x70 <- rnorm(10, mu, sd)
z70 <- rnorm(10, mu, sd)
xz70 <- cbind(x70, z70)
xz70 <- as.data.frame(xz70)
xz70$y70 <- rho * xz70$x70 + (1 - (rho)^2) * xz70$z70
  

xy70 <- xz70 %>%
  filter(x70 <= qnorm(.70))

r70 <- cor(xy70$x70, xy70$y70)
df_nt$n10theta.3[i] <- abs(r70)

#n = 10 theta = .35
x65 <- rnorm(10, mu, sd)
z65 <- rnorm(10, mu, sd)
xz65 <- cbind(x65, z65)
xz65 <- as.data.frame(xz65)
xz65$y65 <- rho * xz65$x65 + (1 - (rho)^2) * xz65$z65

xy65 <- xz65 %>%
  filter(x65 <= qnorm(.65))

r65 <- cor(xy65$x65, xy65$y65)
df_nt$n10theta.35[i] <- abs(r65)

#n = 10 theta = .4
x60 <- rnorm(10, mu, sd)
z60 <- rnorm(10, mu, sd)
xz60 <- cbind(x60, z60)
xz60 <- as.data.frame(xz60)
xz60$y60 <- rho * xz60$x60 + (1 - (rho)^2) * xz60$z60
  

xy60 <- xz60 %>%
  filter(x60 <= qnorm(.60))

r60 <- cor(xy60$x60, xy60$y60)
 df_nt$n10theta.4[i] <- abs(r60)

#n = 15 theta = .05
x95 <- rnorm(15, mu, sd)
z95 <- rnorm(15, mu, sd)
xz95 <- cbind(x95, z95)
xz95 <- as.data.frame(xz95)
xz95$y95 <- rho * xz95$x95 + (1 - (rho)^2) * xz95$z95

xy95 <- xz95 %>%
  filter(x95 <= qnorm(.95))

r95 <- cor(xy95$x95, xy95$y95)
df_nt$n15theta.05[i] <- abs(r95)

#n = 15 theta = .1

x90 <- rnorm(15, mu, sd)
z90 <- rnorm(15, mu, sd)
xz90 <- cbind(x90, z90)
xz90 <- as.data.frame(xz90)
xz90$y90 <- rho * xz90$x90 + (1 - (rho)^2) * xz90$z90


xy90 <- xz90 %>%
  filter(x90 <= qnorm(.90))

r90 <- cor(xy90$x90, xy90$y90)
df_nt$n15theta.1[i] <- abs(r90)

#n = 15 theta = .15
x85 <- rnorm(15, mu, sd)
z85 <- rnorm(15, mu, sd)
xz85 <- cbind(x85, z85)
xz85 <- as.data.frame(xz85)
xz85$y85 <- rho * xz85$x85 + (1 - (rho)^2) * xz85$z85
  

xy85 <- xz85 %>%
  filter(x85 <= qnorm(.85))

r85 <- cor(xy85$x85, xy85$y85)
df_nt$n15theta.15[i] <- abs(r85)

#n = 15 theta = .2
x80 <- rnorm(15, mu, sd)
z80 <- rnorm(15, mu, sd)
xz80 <- cbind(x80, z80)
xz80 <- as.data.frame(xz80)
xz80$y80 <- rho * xz80$x80 + (1 - (rho)^2) * xz80$z80
  

xy80 <- xz80%>%
  filter(x80 <= qnorm(.8))

r80 <- cor(xy80$x80, xy80$y80)
df_nt$n15theta.2[i] <- abs(r80)

#n = 15 theta = .25
x75 <- rnorm(15, mu, sd)
z75 <- rnorm(15, mu, sd)
xz75 <- cbind(x75, z75)
xz75 <- as.data.frame(xz75)
xz75$y75 <- rho * xz75$x75 + (1 - (rho)^2) * xz75$z75
  

xy75 <- xz75 %>%
  filter(x75 <= qnorm(.75))

r75 <- cor(xy75$x75, xy75$y75)
df_nt$n15theta.25[i] <- abs(r75)

#n = 15 theta = .3
x70 <- rnorm(15, mu, sd)
z70 <- rnorm(15, mu, sd)
xz70 <- cbind(x70, z70)
xz70 <- as.data.frame(xz70)
xz70$y70 <- rho * xz70$x70 + (1 - (rho)^2) * xz70$z70
  

xy70 <- xz70 %>%
  filter(x70 <= qnorm(.70))

r70 <- cor(xy70$x70, xy70$y70)
df_nt$n15theta.3[i] <- abs(r70)

#n = 15 theta = .35
x65 <- rnorm(15, mu, sd)
z65 <- rnorm(15, mu, sd)
xz65 <- cbind(x65, z65)
xz65 <- as.data.frame(xz65)
xz65$y65 <- rho * xz65$x65 + (1 - (rho)^2) * xz65$z65

xy65 <- xz65 %>%
  filter(x65 <= qnorm(.65))

r65 <- cor(xy65$x65, xy65$y65)
df_nt$n15theta.35[i] <- abs(r65)

#n = 15 theta = .4
x60 <- rnorm(15, mu, sd)
z60 <- rnorm(15, mu, sd)
xz60 <- cbind(x60, z60)
xz60 <- as.data.frame(xz60)
xz60$y60 <- rho * xz60$x60 + (1 - (rho)^2) * xz60$z60
  

xy60 <- xz60 %>%
  filter(x60 <= qnorm(.60))

r60 <- cor(xy60$x60, xy60$y60)
df_nt$n15theta.4[i] <- abs(r60) 

#n = 20 theta = .05
x95 <- rnorm(20, mu, sd)
z95 <- rnorm(20, mu, sd)
xz95 <- cbind(x95, z95)
xz95 <- as.data.frame(xz95)
xz95$y95 <- rho * xz95$x95 + (1 - (rho)^2) * xz95$z95

xy95 <- xz95 %>%
  filter(x95 <= qnorm(.95))

r95 <- cor(xy95$x95, xy95$y95)
df_nt$n20theta.05[i] <- abs(r95)

#n = 20 theta = .1
x90 <- rnorm(20, mu, sd)
z90 <- rnorm(20, mu, sd)
xz90 <- cbind(x90, z90)
xz90 <- as.data.frame(xz90)
xz90$y90 <- rho * xz90$x90 + (1 - (rho)^2) * xz90$z90
  

xy90 <- xz90 %>%
  filter(x90 <= qnorm(.90))

r90 <- cor(xy90$x90, xy90$y90)
df_nt$n20theta.1[i] <- abs(r90)

#n = 20 theta = .15
x85 <- rnorm(20, mu, sd)
z85 <- rnorm(20, mu, sd)
xz85 <- cbind(x85, z85)
xz85 <- as.data.frame(xz85)
xz85$y85 <- rho * xz85$x85 + (1 - (rho)^2) * xz85$z85
  

xy85 <- xz85 %>%
  filter(x85 <= qnorm(.85))

r85 <- cor(xy85$x85, xy85$y85)
df_nt$n20theta.15[i] <- abs(r85)

#n = 20 theta = .2
x80 <- rnorm(20, mu, sd)
z80 <- rnorm(20, mu, sd)
xz80 <- cbind(x80, z80)
xz80 <- as.data.frame(xz80)
xz80$y80 <- rho * xz80$x80 + (1 - (rho)^2) * xz80$z80
  

xy80 <- xz80%>%
  filter(x80 <= qnorm(.8))

r80 <- cor(xy80$x80, xy80$y80)
df_nt$n20theta.2[i] <- abs(r80)

#n = 20 theta = .25
x75 <- rnorm(20, mu, sd)
z75 <- rnorm(20, mu, sd)
xz75 <- cbind(x75, z75)
xz75 <- as.data.frame(xz75)
xz75$y75 <- rho * xz75$x75 + (1 - (rho)^2) * xz75$z75
  

xy75 <- xz75 %>%
  filter(x75 <= qnorm(.75))

r75 <- cor(xy75$x75, xy75$y75)
df_nt$n20theta.25[i] <- abs(r75)

#n = 20 theta = .3
x70 <- rnorm(20, mu, sd)
z70 <- rnorm(20, mu, sd)
xz70 <- cbind(x70, z70)
xz70 <- as.data.frame(xz70)
xz70$y70 <- rho * xz70$x70 + (1 - (rho)^2) * xz70$z70
  

xy70 <- xz70 %>%
  filter(x70 <= qnorm(.70))

r70 <- cor(xy70$x70, xy70$y70)
df_nt$n20theta.3[i] <- abs(r70)

#n = 20 theta = .35
x65 <- rnorm(20, mu, sd)
z65 <- rnorm(20, mu, sd)
xz65 <- cbind(x65, z65)
xz65 <- as.data.frame(xz65)
xz65$y65 <- rho * xz65$x65 + (1 - (rho)^2) * xz65$z65

xy65 <- xz65 %>%
  filter(x65 <= qnorm(.65))

r65 <- cor(xy65$x65, xy65$y65)
df_nt$n20theta.35[i] <- abs(r65)

#n = 20 theta = .4
x60 <- rnorm(20, mu, sd)
z60 <- rnorm(20, mu, sd)
xz60 <- cbind(x60, z60)
xz60 <- as.data.frame(xz60)
xz60$y60 <- rho * xz60$x60 + (1 - (rho)^2) * xz60$z60
  

xy60 <- xz60 %>%
  filter(x60 <= qnorm(.60))

r60 <- cor(xy60$x60, xy60$y60)
df_nt$n20theta.4[i] <- abs(r60)

#n = 25 theta = .05
x95 <- rnorm(25, mu, sd)
z95 <- rnorm(25, mu, sd)
xz95 <- cbind(x95, z95)
xz95 <- as.data.frame(xz95)
xz95$y95 <- rho * xz95$x95 + (1 - (rho)^2) * xz95$z95

xy95 <- xz95 %>%
  filter(x95 <= qnorm(.95))

r95 <- cor(xy95$x95, xy95$y95)
df_nt$n25theta.05[i] <- abs(r95)

#n = 25 theta = .1
x90 <- rnorm(25, mu, sd)
z90 <- rnorm(25, mu, sd)
xz90 <- cbind(x90, z90)
xz90 <- as.data.frame(xz90)
xz90$y90 <- rho * xz90$x90 + (1 - (rho)^2) * xz90$z90
  

xy90 <- xz90 %>%
  filter(x90 <= qnorm(.90))

r90 <- cor(xy90$x90, xy90$y90)
df_nt$n25theta.1[i] <- abs(r90)

#n = 25 theta = .15
x85 <- rnorm(25, mu, sd)
z85 <- rnorm(25, mu, sd)
xz85 <- cbind(x85, z85)
xz85 <- as.data.frame(xz85)
xz85$y85 <- rho * xz85$x85 + (1 - (rho)^2) * xz85$z85
  

xy85 <- xz85 %>%
  filter(x85 <= qnorm(.85))

r85 <- cor(xy85$x85, xy85$y85)
df_nt$n25theta.15[i] <- abs(r85)

#n = 25 theta = .2
x80 <- rnorm(25, mu, sd)
z80 <- rnorm(25, mu, sd)
xz80 <- cbind(x80, z80)
xz80 <- as.data.frame(xz80)
xz80$y80 <- rho * xz80$x80 + (1 - (rho)^2) * xz80$z80
  

xy80 <- xz80%>%
  filter(x80 <= qnorm(.8))

r80 <- cor(xy80$x80, xy80$y80)
df_nt$n25theta.2[i] <- abs(r80)

#n = 25 theta = .25
x75 <- rnorm(25, mu, sd)
z75 <- rnorm(25, mu, sd)
xz75 <- cbind(x75, z75)
xz75 <- as.data.frame(xz75)
xz75$y75 <- rho * xz75$x75 + (1 - (rho)^2) * xz75$z75
  

xy75 <- xz75 %>%
  filter(x75 <= qnorm(.75))

r75 <- cor(xy75$x75, xy75$y75)
df_nt$n25theta.25[i] <- abs(r75)

#n = 25 theta = .3
x70 <- rnorm(25, mu, sd)
z70 <- rnorm(25, mu, sd)
xz70 <- cbind(x70, z70)
xz70 <- as.data.frame(xz70)
xz70$y70 <- rho * xz70$x70 + (1 - (rho)^2) * xz70$z70
  

xy70 <- xz70 %>%
  filter(x70 <= qnorm(.70))

r70 <- cor(xy70$x70, xy70$y70)
df_nt$n25theta.3[i] <- abs(r70)

#n = 25 theta = .35
x65 <- rnorm(25, mu, sd)
z65 <- rnorm(25, mu, sd)
xz65 <- cbind(x65, z65)
xz65 <- as.data.frame(xz65)
xz65$y65 <- rho * xz65$x65 + (1 - (rho)^2) * xz65$z65

xy65 <- xz65 %>%
  filter(x65 <= qnorm(.65))

r65 <- cor(xy65$x65, xy65$y65)
df_nt$n25theta.35[i] <- abs(r65)

#n = 25 theta = .4
x60 <- rnorm(25, mu, sd)
z60 <- rnorm(25, mu, sd)
xz60 <- cbind(x60, z60)
xz60 <- as.data.frame(xz60)
xz60$y60 <- rho * xz60$x60 + (1 - (rho)^2) * xz60$z60
  

xy60 <- xz60 %>%
  filter(x60 <= qnorm(.60))

r60 <- cor(xy60$x60, xy60$y60)
df_nt$n25theta.4[i] <- abs(r60)

#n = 30 theta = .05
x95 <- rnorm(30, mu, sd)
z95 <- rnorm(30, mu, sd)
xz95 <- cbind(x95, z95)
xz95 <- as.data.frame(xz95)
xz95$y95 <- rho * xz95$x95 + (1 - (rho)^2) * xz95$z95


xy95 <- xz95 %>%
  filter(x95 <= qnorm(.95))

r95 <- cor(xy95$x95, xy95$y95)
df_nt$n30theta.05[i] <- abs(r95)

#n = 30 theta = .1
x90 <- rnorm(30, mu, sd)
z90 <- rnorm(30, mu, sd)
xz90 <- cbind(x90, z90)
xz90 <- as.data.frame(xz90)
xz90$y90 <- rho * xz90$x90 + (1 - (rho)^2) * xz90$z90

xy90 <- xz90 %>%
  filter(x90 <= qnorm(.90))

r90 <- cor(xy90$x90, xy90$y90)
df_nt$n30theta.1[i] <- abs(r90)

#n = 30 theta = .15
x85 <- rnorm(30, mu, sd)
z85 <- rnorm(30, mu, sd)
xz85 <- cbind(x85, z85)
xz85 <- as.data.frame(xz85)
xz85$y85 <- rho * xz85$x85 + (1 - (rho)^2) * xz85$z85
  
xy85 <- xz85 %>%
  filter(x85 <= qnorm(.85))

r85 <- cor(xy85$x85, xy85$y85)
df_nt$n30theta.15[i] <- abs(r85)

#n = 30 theta = .2
x80 <- rnorm(30, mu, sd)
z80 <- rnorm(30, mu, sd)
xz80 <- cbind(x80, z80)
xz80 <- as.data.frame(xz80)
xz80$y80 <- rho * xz80$x80 + (1 - (rho)^2) * xz80$z80
  

xy80 <- xz80%>%
  filter(x80 <= qnorm(.8))

r80 <- cor(xy80$x80, xy80$y80)
df_nt$n30theta.2[i] <- abs(r80)

#n = 30 theta = .25
x75 <- rnorm(30, mu, sd)
z75 <- rnorm(30, mu, sd)
xz75 <- cbind(x75, z75)
xz75 <- as.data.frame(xz75)
xz75$y75 <- rho * xz75$x75 + (1 - (rho)^2) * xz75$z75
  

xy75 <- xz75 %>%
  filter(x75 <= qnorm(.75))

r75 <- cor(xy75$x75, xy75$y75)
df_nt$n30theta.25[i] <- abs(r75)

#n = 30 theta = .3
x70 <- rnorm(30, mu, sd)
z70 <- rnorm(30, mu, sd)
xz70 <- cbind(x70, z70)
xz70 <- as.data.frame(xz70)
xz70$y70 <- rho * xz70$x70 + (1 - (rho)^2) * xz70$z70
  

xy70 <- xz70 %>%
  filter(x70 <= qnorm(.70))

r70 <- cor(xy70$x70, xy70$y70)
df_nt$n30theta.3[i] <- abs(r70)

#n = 30 theta = .35
x65 <- rnorm(30, mu, sd)
z65 <- rnorm(30, mu, sd)
xz65 <- cbind(x65, z65)
xz65 <- as.data.frame(xz65)
xz65$y65 <- rho * xz65$x65 + (1 - (rho)^2) * xz65$z65

xy65 <- xz65 %>%
  filter(x65 <= qnorm(.65))

r65 <- cor(xy65$x65, xy65$y65)
df_nt$n30theta.35[i] <- abs(r65)

#n = 30 theta = .4
x60 <- rnorm(30, mu, sd)
z60 <- rnorm(30, mu, sd)
xz60 <- cbind(x60, z60)
xz60 <- as.data.frame(xz60)
xz60$y60 <- rho * xz60$x60 + (1 - (rho)^2) * xz60$z60
  

xy60 <- xz60 %>%
  filter(x60 <= qnorm(.60))

r60 <- cor(xy60$x60, xy60$y60)
df_nt$n30theta.4[i] <- abs(r60)

#n = 35 theta = .05
x95 <- rnorm(35, mu, sd)
z95 <- rnorm(35, mu, sd)
xz95 <- cbind(x95, z95)
xz95 <- as.data.frame(xz95)
xz95$y95 <- rho * xz95$x95 + (1 - (rho)^2) * xz95$z95

xy95 <- xz95 %>%
  filter(x95 <= qnorm(.95))

r95 <- cor(xy95$x95, xy95$y95)
df_nt$n35theta.05[i] <- abs(r95)

#n = 35 theta = .1

x90 <- rnorm(35, mu, sd)
z90 <- rnorm(35, mu, sd)
xz90 <- cbind(x90, z90)
xz90 <- as.data.frame(xz90)
xz90$y90 <- rho * xz90$x90 + (1 - (rho)^2) * xz90$z90


xy90 <- xz90 %>%
  filter(x90 <= qnorm(.90))

r90 <- cor(xy90$x90, xy90$y90)
df_nt$n35theta.1[i] <- abs(r90)

#n = 35 theta = .15
x85 <- rnorm(35, mu, sd)
z85 <- rnorm(35, mu, sd)
xz85 <- cbind(x85, z85)
xz85 <- as.data.frame(xz85)
xz85$y85 <- rho * xz85$x85 + (1 - (rho)^2) * xz85$z85
  

xy85 <- xz85 %>%
  filter(x85 <= qnorm(.85))

r85 <- cor(xy85$x85, xy85$y85)
df_nt$n35theta.15[i] <- abs(r85)

#n = 35 theta = .2
x80 <- rnorm(35, mu, sd)
z80 <- rnorm(35, mu, sd)
xz80 <- cbind(x80, z80)
xz80 <- as.data.frame(xz80)
xz80$y80 <- rho * xz80$x80 + (1 - (rho)^2) * xz80$z80
  

xy80 <- xz80%>%
  filter(x80 <= qnorm(.8))

r80 <- cor(xy80$x80, xy80$y80)
df_nt$n35theta.2[i] <- abs(r80)

#n = 35 theta = .25
x75 <- rnorm(35, mu, sd)
z75 <- rnorm(35, mu, sd)
xz75 <- cbind(x75, z75)
xz75 <- as.data.frame(xz75)
xz75$y75 <- rho * xz75$x75 + (1 - (rho)^2) * xz75$z75
  

xy75 <- xz75 %>%
  filter(x75 <= qnorm(.75))

r75 <- cor(xy75$x75, xy75$y75)
df_nt$n35theta.25[i] <- abs(r75)

#n = 35 theta = .3
x70 <- rnorm(35, mu, sd)
z70 <- rnorm(35, mu, sd)
xz70 <- cbind(x70, z70)
xz70 <- as.data.frame(xz70)
xz70$y70 <- rho * xz70$x70 + (1 - (rho)^2) * xz70$z70
  

xy70 <- xz70 %>%
  filter(x70 <= qnorm(.70))

r70 <- cor(xy70$x70, xy70$y70)
df_nt$n35theta.3[i] <- abs(r70)

#n = 35 theta = .35
x65 <- rnorm(35, mu, sd)
z65 <- rnorm(35, mu, sd)
xz65 <- cbind(x65, z65)
xz65 <- as.data.frame(xz65)
xz65$y65 <- rho * xz65$x65 + (1 - (rho)^2) * xz65$z65

xy65 <- xz65 %>%
  filter(x65 <= qnorm(.65))

r65 <- cor(xy65$x65, xy65$y65)
df_nt$n35theta.35[i] <- abs(r65)

#n = 35 theta = .4
x60 <- rnorm(35, mu, sd)
z60 <- rnorm(35, mu, sd)
xz60 <- cbind(x60, z60)
xz60 <- as.data.frame(xz60)
xz60$y60 <- rho * xz60$x60 + (1 - (rho)^2) * xz60$z60
  

xy60 <- xz60 %>%
  filter(x60 <= qnorm(.60))

r60 <- cor(xy60$x60, xy60$y60)
df_nt$n35theta.4[i] <- abs(r60)

#n = 40 theta = .05
x95 <- rnorm(40, mu, sd)
z95 <- rnorm(40, mu, sd)
xz95 <- cbind(x95, z95)
xz95 <- as.data.frame(xz95)
xz95$y95 <- rho * xz95$x95 + (1 - (rho)^2) * xz95$z95

xy95 <- xz95 %>%
  filter(x95 <= qnorm(.95))

r95 <- cor(xy95$x95, xy95$y95)
df_nt$n40theta.05[i] <- abs(r95)

#n = 40 theta = .1
x90 <- rnorm(40, mu, sd)
z90 <- rnorm(40, mu, sd)
xz90 <- cbind(x90, z90)
xz90 <- as.data.frame(xz90)
xz90$y90 <- rho * xz90$x90 + (1 - (rho)^2) * xz90$z90
  

xy90 <- xz90 %>%
  filter(x90 <= qnorm(.90))

r90 <- cor(xy90$x90, xy90$y90)
df_nt$n40theta.1[i] <- abs(r90)

#n = 40 theta = .15
x85 <- rnorm(40, mu, sd)
z85 <- rnorm(40, mu, sd)
xz85 <- cbind(x85, z85)
xz85 <- as.data.frame(xz85)
xz85$y85 <- rho * xz85$x85 + (1 - (rho)^2) * xz85$z85
  

xy85 <- xz85 %>%
  filter(x85 <= qnorm(.85))

r85 <- cor(xy85$x85, xy85$y85)
df_nt$n40theta.15[i] <- abs(r85)

#n = 40 theta = .2
x80 <- rnorm(40, mu, sd)
z80 <- rnorm(40, mu, sd)
xz80 <- cbind(x80, z80)
xz80 <- as.data.frame(xz80)
xz80$y80 <- rho * xz80$x80 + (1 - (rho)^2) * xz80$z80
  

xy80 <- xz80%>%
  filter(x80 <= qnorm(.8))

r80 <- cor(xy80$x80, xy80$y80)
df_nt$n40theta.2[i] <- abs(r80)

#n = 40 theta = .25
x75 <- rnorm(40, mu, sd)
z75 <- rnorm(40, mu, sd)
xz75 <- cbind(x75, z75)
xz75 <- as.data.frame(xz75)
xz75$y75 <- rho * xz75$x75 + (1 - (rho)^2) * xz75$z75
  

xy75 <- xz75 %>%
  filter(x75 <= qnorm(.75))

r75 <- cor(xy75$x75, xy75$y75)
df_nt$n40theta.25[i] <- abs(r75)

#n = 40 theta = .3
x70 <- rnorm(40, mu, sd)
z70 <- rnorm(40, mu, sd)
xz70 <- cbind(x70, z70)
xz70 <- as.data.frame(xz70)
xz70$y70 <- rho * xz70$x70 + (1 - (rho)^2) * xz70$z70
  

xy70 <- xz70 %>%
  filter(x70 <= qnorm(.70))

r70 <- cor(xy70$x70, xy70$y70)
df_nt$n40theta.3[i] <- abs(r70)

#n = 40 theta = .35
x65 <- rnorm(40, mu, sd)
z65 <- rnorm(40, mu, sd)
xz65 <- cbind(x65, z65)
xz65 <- as.data.frame(xz65)
xz65$y65 <- rho * xz65$x65 + (1 - (rho)^2) * xz65$z65

xy65 <- xz65 %>%
  filter(x65 <= qnorm(.65))

r65 <- cor(xy65$x65, xy65$y65)
df_nt$n40theta.35[i] <- abs(r65)

#n = 40 theta = .4
x60 <- rnorm(40, mu, sd)
z60 <- rnorm(40, mu, sd)
xz60 <- cbind(x60, z60)
xz60 <- as.data.frame(xz60)
xz60$y60 <- rho * xz60$x60 + (1 - (rho)^2) * xz60$z60
  

xy60 <- xz60 %>%
  filter(x60 <= qnorm(.60))

r60 <- cor(xy60$x60, xy60$y60)
df_nt$n40theta.4[i] <- abs(r60)

}
  #n = 10 theta = .05
  quantiles$n10theta.05.1[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 < b10.05.1])
  quantiles$n10theta.05.2[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 < b10.05.2 & df_nt$n10theta.05 > b10.05.1])
  quantiles$n10theta.05.3[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 < b10.05.3 & df_nt$n10theta.05 > b10.05.2])
  quantiles$n10theta.05.4[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 < b10.05.4 & df_nt$n10theta.05 > b10.05.3])
  quantiles$n10theta.05.5[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 < b10.05.5 & df_nt$n10theta.05 > b10.05.4])
  quantiles$n10theta.05.6[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 < b10.05.6 & df_nt$n10theta.05 > b10.05.5])
  quantiles$n10theta.05.7[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 < b10.05.7 & df_nt$n10theta.05 > b10.05.6])
  quantiles$n10theta.05.8[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 < b10.05.8 & df_nt$n10theta.05 > b10.05.7])
  quantiles$n10theta.05.9[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 < b10.05.9 & df_nt$n10theta.05 > b10.05.8])
  quantiles$n10theta.051[h] <- length(df_nt$n10theta.05[df_nt$n10theta.05 > b10.05.9])
  
  #n = 10 theta = .1
  quantiles$n10theta.1.1[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 < b10.1.1])
  quantiles$n10theta.1.2[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 < b10.1.2 & df_nt$n10theta.1 > b10.1.1])
  quantiles$n10theta.1.3[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 < b10.1.3 & df_nt$n10theta.1 > b10.1.2])
  quantiles$n10theta.1.4[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 < b10.1.4 & df_nt$n10theta.1 > b10.1.3])
  quantiles$n10theta.1.5[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 < b10.1.5 & df_nt$n10theta.1 > b10.1.4])
  quantiles$n10theta.1.6[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 < b10.1.6 & df_nt$n10theta.1 > b10.1.5])
  quantiles$n10theta.1.7[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 < b10.1.7 & df_nt$n10theta.1 > b10.1.6])
  quantiles$n10theta.1.8[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 < b10.1.8 & df_nt$n10theta.1 > b10.1.7])
  quantiles$n10theta.1.9[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 < b10.1.9 & df_nt$n10theta.1 > b10.1.8])
  quantiles$n10theta.11[h] <- length(df_nt$n10theta.1[df_nt$n10theta.1 > b10.1.9])
  
  #n = 10 theta = .15
  quantiles$n10theta.15.1[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 < b10.15.1])
  quantiles$n10theta.15.2[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 < b10.15.2 & df_nt$n10theta.15 > b10.15.1])
  quantiles$n10theta.15.3[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 < b10.15.3 & df_nt$n10theta.15 > b10.15.2])
  quantiles$n10theta.15.4[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 < b10.15.4 & df_nt$n10theta.15 > b10.15.3])
  quantiles$n10theta.15.5[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 < b10.15.5 & df_nt$n10theta.15 > b10.15.4])
  quantiles$n10theta.15.6[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 < b10.15.6 & df_nt$n10theta.15 > b10.15.5])
  quantiles$n10theta.15.7[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 < b10.15.7 & df_nt$n10theta.15 > b10.15.6])
  quantiles$n10theta.15.8[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 < b10.15.8 & df_nt$n10theta.15 > b10.15.7])
  quantiles$n10theta.15.9[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 < b10.15.9 & df_nt$n10theta.15 > b10.15.8])
  quantiles$n10theta.151[h] <- length(df_nt$n10theta.15[df_nt$n10theta.15 > b10.15.9])
  
  #n = 10 theta = .2
  quantiles$n10theta.2.1[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 < b10.2.1])
  quantiles$n10theta.2.2[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 < b10.2.2 & df_nt$n10theta.2 > b10.2.1])
  quantiles$n10theta.2.3[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 < b10.2.3 & df_nt$n10theta.2 > b10.2.2])
  quantiles$n10theta.2.4[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 < b10.2.4 & df_nt$n10theta.2 > b10.2.3])
  quantiles$n10theta.2.5[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 < b10.2.5 & df_nt$n10theta.2 > b10.2.4])
  quantiles$n10theta.2.6[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 < b10.2.6 & df_nt$n10theta.2 > b10.2.5])
  quantiles$n10theta.2.7[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 < b10.2.7 & df_nt$n10theta.2 > b10.2.6])
  quantiles$n10theta.2.8[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 < b10.2.8 & df_nt$n10theta.2 > b10.2.7])
  quantiles$n10theta.2.9[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 < b10.2.9 & df_nt$n10theta.2 > b10.2.8])
  quantiles$n10theta.21[h] <- length(df_nt$n10theta.2[df_nt$n10theta.2 > b10.2.9])
  
  #n = 10 theta = .25
  quantiles$n10theta.25.1[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 < b10.25.1])
  quantiles$n10theta.25.2[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 < b10.25.2 & df_nt$n10theta.25 > b10.25.1])
  quantiles$n10theta.25.3[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 < b10.25.3 & df_nt$n10theta.25 > b10.25.2])
  quantiles$n10theta.25.4[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 < b10.25.4 & df_nt$n10theta.25 > b10.25.3])
  quantiles$n10theta.25.5[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 < b10.25.5 & df_nt$n10theta.25 > b10.25.4])
  quantiles$n10theta.25.6[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 < b10.25.6 & df_nt$n10theta.25 > b10.25.5])
  quantiles$n10theta.25.7[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 < b10.25.7 & df_nt$n10theta.25 > b10.25.6])
  quantiles$n10theta.25.8[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 < b10.25.8 & df_nt$n10theta.25 > b10.25.7])
  quantiles$n10theta.25.9[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 < b10.25.9 & df_nt$n10theta.25 > b10.25.8])
  quantiles$n10theta.251[h] <- length(df_nt$n10theta.25[df_nt$n10theta.25 > b10.25.9])
  
  #n = 10 theta = .3
  quantiles$n10theta.3.1[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 < b10.3.1])
  quantiles$n10theta.3.2[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 < b10.3.2 & df_nt$n10theta.3 > b10.3.1])
  quantiles$n10theta.3.3[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 < b10.3.3 & df_nt$n10theta.3 > b10.3.2])
  quantiles$n10theta.3.4[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 < b10.3.4 & df_nt$n10theta.3 > b10.3.3])
  quantiles$n10theta.3.5[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 < b10.3.5 & df_nt$n10theta.3 > b10.3.4])
  quantiles$n10theta.3.6[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 < b10.3.6 & df_nt$n10theta.3 > b10.3.5])
  quantiles$n10theta.3.7[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 < b10.3.7 & df_nt$n10theta.3 > b10.3.6])
  quantiles$n10theta.3.8[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 < b10.3.8 & df_nt$n10theta.3 > b10.3.7])
  quantiles$n10theta.3.9[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 < b10.3.9 & df_nt$n10theta.3 > b10.3.8])
  quantiles$n10theta.31[h] <- length(df_nt$n10theta.3[df_nt$n10theta.3 > b10.3.9])
  
  #n = 10 theta = .35
  quantiles$n10theta.35.1[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 < b10.35.1])
  quantiles$n10theta.35.2[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 < b10.35.2 & df_nt$n10theta.35 > b10.35.1])
  quantiles$n10theta.35.3[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 < b10.35.3 & df_nt$n10theta.35 > b10.35.2])
  quantiles$n10theta.35.4[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 < b10.35.4 & df_nt$n10theta.35 > b10.35.3])
  quantiles$n10theta.35.5[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 < b10.35.5 & df_nt$n10theta.35 > b10.35.4])
  quantiles$n10theta.35.6[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 < b10.35.6 & df_nt$n10theta.35 > b10.35.5])
  quantiles$n10theta.35.7[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 < b10.35.7 & df_nt$n10theta.35 > b10.35.6])
  quantiles$n10theta.35.8[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 < b10.35.8 & df_nt$n10theta.35 > b10.35.7])
  quantiles$n10theta.35.9[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 < b10.35.9 & df_nt$n10theta.35 > b10.35.8])
  quantiles$n10theta.351[h] <- length(df_nt$n10theta.35[df_nt$n10theta.35 > b10.35.9])
  
  #n = 10 theta = .4
  quantiles$n10theta.4.1[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 < b10.4.1])
  quantiles$n10theta.4.2[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 < b10.4.2 & df_nt$n10theta.4 > b10.4.1])
  quantiles$n10theta.4.3[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 < b10.4.3 & df_nt$n10theta.4 > b10.4.2])
  quantiles$n10theta.4.4[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 < b10.4.4 & df_nt$n10theta.4 > b10.4.3])
  quantiles$n10theta.4.5[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 < b10.4.5 & df_nt$n10theta.4 > b10.4.4])
  quantiles$n10theta.4.6[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 < b10.4.6 & df_nt$n10theta.4 > b10.4.5])
  quantiles$n10theta.4.7[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 < b10.4.7 & df_nt$n10theta.4 > b10.4.6])
  quantiles$n10theta.4.8[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 < b10.4.8 & df_nt$n10theta.4 > b10.4.7])
  quantiles$n10theta.4.9[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 < b10.4.9 & df_nt$n10theta.4 > b10.4.8])
  quantiles$n10theta.41[h] <- length(df_nt$n10theta.4[df_nt$n10theta.4 > b10.4.9])
  
  #n = 15 theta = .05
  quantiles$n15theta.05.1[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 < b15.05.1])
  quantiles$n15theta.05.2[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 < b15.05.2 & df_nt$n15theta.05 > b15.05.1])
  quantiles$n15theta.05.3[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 < b15.05.3 & df_nt$n15theta.05 > b15.05.2])
  quantiles$n15theta.05.4[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 < b15.05.4 & df_nt$n15theta.05 > b15.05.3])
  quantiles$n15theta.05.5[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 < b15.05.5 & df_nt$n15theta.05 > b15.05.4])
  quantiles$n15theta.05.6[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 < b15.05.6 & df_nt$n15theta.05 > b15.05.5])
  quantiles$n15theta.05.7[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 < b15.05.7 & df_nt$n15theta.05 > b15.05.6])
  quantiles$n15theta.05.8[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 < b15.05.8 & df_nt$n15theta.05 > b15.05.7])
  quantiles$n15theta.05.9[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 < b15.05.9 & df_nt$n15theta.05 > b15.05.8])
  quantiles$n15theta.051[h] <- length(df_nt$n15theta.05[df_nt$n15theta.05 > b15.05.9])
  
  #n = 15 theta = .1
  quantiles$n15theta.1.1[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 < b15.1.1])
  quantiles$n15theta.1.2[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 < b15.1.2 & df_nt$n15theta.1 > b15.1.1])
  quantiles$n15theta.1.3[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 < b15.1.3 & df_nt$n15theta.1 > b15.1.2])
  quantiles$n15theta.1.4[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 < b15.1.4 & df_nt$n15theta.1 > b15.1.3])
  quantiles$n15theta.1.5[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 < b15.1.5 & df_nt$n15theta.1 > b15.1.4])
  quantiles$n15theta.1.6[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 < b15.1.6 & df_nt$n15theta.1 > b15.1.5])
  quantiles$n15theta.1.7[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 < b15.1.7 & df_nt$n15theta.1 > b15.1.6])
  quantiles$n15theta.1.8[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 < b15.1.8 & df_nt$n15theta.1 > b15.1.7])
  quantiles$n15theta.1.9[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 < b15.1.9 & df_nt$n15theta.1 > b15.1.8])
  quantiles$n15theta.11[h] <- length(df_nt$n15theta.1[df_nt$n15theta.1 > b15.1.9])
  
  #n = 15 theta = .15
  quantiles$n15theta.15.1[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 < b15.15.1])
  quantiles$n15theta.15.2[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 < b15.15.2 & df_nt$n15theta.15 > b15.15.1])
  quantiles$n15theta.15.3[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 < b15.15.3 & df_nt$n15theta.15 > b15.15.2])
  quantiles$n15theta.15.4[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 < b15.15.4 & df_nt$n15theta.15 > b15.15.3])
  quantiles$n15theta.15.5[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 < b15.15.5 & df_nt$n15theta.15 > b15.15.4])
  quantiles$n15theta.15.6[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 < b15.15.6 & df_nt$n15theta.15 > b15.15.5])
  quantiles$n15theta.15.7[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 < b15.15.7 & df_nt$n15theta.15 > b15.15.6])
  quantiles$n15theta.15.8[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 < b15.15.8 & df_nt$n15theta.15 > b15.15.7])
  quantiles$n15theta.15.9[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 < b15.15.9 & df_nt$n15theta.15 > b15.15.8])
  quantiles$n15theta.151[h] <- length(df_nt$n15theta.15[df_nt$n15theta.15 > b15.15.9])
  
  #n = 15 theta = .2
  quantiles$n15theta.2.1[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 < b15.2.1])
  quantiles$n15theta.2.2[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 < b15.2.2 & df_nt$n15theta.2 > b15.2.1])
  quantiles$n15theta.2.3[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 < b15.2.3 & df_nt$n15theta.2 > b15.2.2])
  quantiles$n15theta.2.4[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 < b15.2.4 & df_nt$n15theta.2 > b15.2.3])
  quantiles$n15theta.2.5[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 < b15.2.5 & df_nt$n15theta.2 > b15.2.4])
  quantiles$n15theta.2.6[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 < b15.2.6 & df_nt$n15theta.2 > b15.2.5])
  quantiles$n15theta.2.7[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 < b15.2.7 & df_nt$n15theta.2 > b15.2.6])
  quantiles$n15theta.2.8[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 < b15.2.8 & df_nt$n15theta.2 > b15.2.7])
  quantiles$n15theta.2.9[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 < b15.2.9 & df_nt$n15theta.2 > b15.2.8])
  quantiles$n15theta.21[h] <- length(df_nt$n15theta.2[df_nt$n15theta.2 > b15.2.9])
  
  #n = 15 theta = .25
  quantiles$n15theta.25.1[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 < b15.25.1])
  quantiles$n15theta.25.2[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 < b15.25.2 & df_nt$n15theta.25 > b15.25.1])
  quantiles$n15theta.25.3[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 < b15.25.3 & df_nt$n15theta.25 > b15.25.2])
  quantiles$n15theta.25.4[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 < b15.25.4 & df_nt$n15theta.25 > b15.25.3])
  quantiles$n15theta.25.5[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 < b15.25.5 & df_nt$n15theta.25 > b15.25.4])
  quantiles$n15theta.25.6[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 < b15.25.6 & df_nt$n15theta.25 > b15.25.5])
  quantiles$n15theta.25.7[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 < b15.25.7 & df_nt$n15theta.25 > b15.25.6])
  quantiles$n15theta.25.8[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 < b15.25.8 & df_nt$n15theta.25 > b15.25.7])
  quantiles$n15theta.25.9[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 < b15.25.9 & df_nt$n15theta.25 > b15.25.8])
  quantiles$n15theta.251[h] <- length(df_nt$n15theta.25[df_nt$n15theta.25 > b15.25.9])
  
  #n = 15 theta = .3
  quantiles$n15theta.3.1[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 < b15.3.1])
  quantiles$n15theta.3.2[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 < b15.3.2 & df_nt$n15theta.3 > b15.3.1])
  quantiles$n15theta.3.3[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 < b15.3.3 & df_nt$n15theta.3 > b15.3.2])
  quantiles$n15theta.3.4[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 < b15.3.4 & df_nt$n15theta.3 > b15.3.3])
  quantiles$n15theta.3.5[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 < b15.3.5 & df_nt$n15theta.3 > b15.3.4])
  quantiles$n15theta.3.6[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 < b15.3.6 & df_nt$n15theta.3 > b15.3.5])
  quantiles$n15theta.3.7[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 < b15.3.7 & df_nt$n15theta.3 > b15.3.6])
  quantiles$n15theta.3.8[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 < b15.3.8 & df_nt$n15theta.3 > b15.3.7])
  quantiles$n15theta.3.9[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 < b15.3.9 & df_nt$n15theta.3 > b15.3.8])
  quantiles$n15theta.31[h] <- length(df_nt$n15theta.3[df_nt$n15theta.3 > b15.3.9])
  
  #n = 15 theta = .35
  quantiles$n15theta.35.1[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 < b15.35.1])
  quantiles$n15theta.35.2[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 < b15.35.2 & df_nt$n15theta.35 > b15.35.1])
  quantiles$n15theta.35.3[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 < b15.35.3 & df_nt$n15theta.35 > b15.35.2])
  quantiles$n15theta.35.4[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 < b15.35.4 & df_nt$n15theta.35 > b15.35.3])
  quantiles$n15theta.35.5[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 < b15.35.5 & df_nt$n15theta.35 > b15.35.4])
  quantiles$n15theta.35.6[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 < b15.35.6 & df_nt$n15theta.35 > b15.35.5])
  quantiles$n15theta.35.7[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 < b15.35.7 & df_nt$n15theta.35 > b15.35.6])
  quantiles$n15theta.35.8[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 < b15.35.8 & df_nt$n15theta.35 > b15.35.7])
  quantiles$n15theta.35.9[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 < b15.35.9 & df_nt$n15theta.35 > b15.35.8])
  quantiles$n15theta.351[h] <- length(df_nt$n15theta.35[df_nt$n15theta.35 > b15.35.9])
  
  #n = 15 theta = .4
  quantiles$n15theta.4.1[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 < b15.4.1])
  quantiles$n15theta.4.2[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 < b15.4.2 & df_nt$n15theta.4 > b15.4.1])
  quantiles$n15theta.4.3[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 < b15.4.3 & df_nt$n15theta.4 > b15.4.2])
  quantiles$n15theta.4.4[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 < b15.4.4 & df_nt$n15theta.4 > b15.4.3])
  quantiles$n15theta.4.5[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 < b15.4.5 & df_nt$n15theta.4 > b15.4.4])
  quantiles$n15theta.4.6[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 < b15.4.6 & df_nt$n15theta.4 > b15.4.5])
  quantiles$n15theta.4.7[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 < b15.4.7 & df_nt$n15theta.4 > b15.4.6])
  quantiles$n15theta.4.8[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 < b15.4.8 & df_nt$n15theta.4 > b15.4.7])
  quantiles$n15theta.4.9[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 < b15.4.9 & df_nt$n15theta.4 > b15.4.8])
  quantiles$n15theta.41[h] <- length(df_nt$n15theta.4[df_nt$n15theta.4 > b15.4.9])
  
  #n = 20 theta = .05
  quantiles$n20theta.05.1[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 < b20.05.1])
  quantiles$n20theta.05.2[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 < b20.05.2 & df_nt$n20theta.05 > b20.05.1])
  quantiles$n20theta.05.3[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 < b20.05.3 & df_nt$n20theta.05 > b20.05.2])
  quantiles$n20theta.05.4[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 < b20.05.4 & df_nt$n20theta.05 > b20.05.3])
  quantiles$n20theta.05.5[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 < b20.05.5 & df_nt$n20theta.05 > b20.05.4])
  quantiles$n20theta.05.6[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 < b20.05.6 & df_nt$n20theta.05 > b20.05.5])
  quantiles$n20theta.05.7[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 < b20.05.7 & df_nt$n20theta.05 > b20.05.6])
  quantiles$n20theta.05.8[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 < b20.05.8 & df_nt$n20theta.05 > b20.05.7])
  quantiles$n20theta.05.9[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 < b20.05.9 & df_nt$n20theta.05 > b20.05.8])
  quantiles$n20theta.051[h] <- length(df_nt$n20theta.05[df_nt$n20theta.05 > b20.05.9])
  
  #n = 20 theta = .1
  quantiles$n20theta.1.1[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 < b20.1.1])
  quantiles$n20theta.1.2[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 < b20.1.2 & df_nt$n20theta.1 > b20.1.1])
  quantiles$n20theta.1.3[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 < b20.1.3 & df_nt$n20theta.1 > b20.1.2])
  quantiles$n20theta.1.4[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 < b20.1.4 & df_nt$n20theta.1 > b20.1.3])
  quantiles$n20theta.1.5[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 < b20.1.5 & df_nt$n20theta.1 > b20.1.4])
  quantiles$n20theta.1.6[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 < b20.1.6 & df_nt$n20theta.1 > b20.1.5])
  quantiles$n20theta.1.7[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 < b20.1.7 & df_nt$n20theta.1 > b20.1.6])
  quantiles$n20theta.1.8[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 < b20.1.8 & df_nt$n20theta.1 > b20.1.7])
  quantiles$n20theta.1.9[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 < b20.1.9 & df_nt$n20theta.1 > b20.1.8])
  quantiles$n20theta.11[h] <- length(df_nt$n20theta.1[df_nt$n20theta.1 > b20.1.9])
  
  #n = 20 theta = .15
  quantiles$n20theta.15.1[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 < b20.15.1])
  quantiles$n20theta.15.2[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 < b20.15.2 & df_nt$n20theta.15 > b20.15.1])
  quantiles$n20theta.15.3[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 < b20.15.3 & df_nt$n20theta.15 > b20.15.2])
  quantiles$n20theta.15.4[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 < b20.15.4 & df_nt$n20theta.15 > b20.15.3])
  quantiles$n20theta.15.5[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 < b20.15.5 & df_nt$n20theta.15 > b20.15.4])
  quantiles$n20theta.15.6[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 < b20.15.6 & df_nt$n20theta.15 > b20.15.5])
  quantiles$n20theta.15.7[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 < b20.15.7 & df_nt$n20theta.15 > b20.15.6])
  quantiles$n20theta.15.8[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 < b20.15.8 & df_nt$n20theta.15 > b20.15.7])
  quantiles$n20theta.15.9[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 < b20.15.9 & df_nt$n20theta.15 > b20.15.8])
  quantiles$n20theta.151[h] <- length(df_nt$n20theta.15[df_nt$n20theta.15 > b20.15.9])
  
  #n = 20 theta = .2
  quantiles$n20theta.2.1[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 < b20.2.1])
  quantiles$n20theta.2.2[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 < b20.2.2 & df_nt$n20theta.2 > b20.2.1])
  quantiles$n20theta.2.3[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 < b20.2.3 & df_nt$n20theta.2 > b20.2.2])
  quantiles$n20theta.2.4[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 < b20.2.4 & df_nt$n20theta.2 > b20.2.3])
  quantiles$n20theta.2.5[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 < b20.2.5 & df_nt$n20theta.2 > b20.2.4])
  quantiles$n20theta.2.6[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 < b20.2.6 & df_nt$n20theta.2 > b20.2.5])
  quantiles$n20theta.2.7[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 < b20.2.7 & df_nt$n20theta.2 > b20.2.6])
  quantiles$n20theta.2.8[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 < b20.2.8 & df_nt$n20theta.2 > b20.2.7])
  quantiles$n20theta.2.9[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 < b20.2.9 & df_nt$n20theta.2 > b20.2.8])
  quantiles$n20theta.21[h] <- length(df_nt$n20theta.2[df_nt$n20theta.2 > b20.2.9])
  
  #n = 20 theta = .25
  quantiles$n20theta.25.1[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 < b20.25.1])
  quantiles$n20theta.25.2[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 < b20.25.2 & df_nt$n20theta.25 > b20.25.1])
  quantiles$n20theta.25.3[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 < b20.25.3 & df_nt$n20theta.25 > b20.25.2])
  quantiles$n20theta.25.4[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 < b20.25.4 & df_nt$n20theta.25 > b20.25.3])
  quantiles$n20theta.25.5[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 < b20.25.5 & df_nt$n20theta.25 > b20.25.4])
  quantiles$n20theta.25.6[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 < b20.25.6 & df_nt$n20theta.25 > b20.25.5])
  quantiles$n20theta.25.7[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 < b20.25.7 & df_nt$n20theta.25 > b20.25.6])
  quantiles$n20theta.25.8[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 < b20.25.8 & df_nt$n20theta.25 > b20.25.7])
  quantiles$n20theta.25.9[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 < b20.25.9 & df_nt$n20theta.25 > b20.25.8])
  quantiles$n20theta.251[h] <- length(df_nt$n20theta.25[df_nt$n20theta.25 > b20.25.9])
  
  #n = 20 theta = .3
  quantiles$n20theta.3.1[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 < b20.3.1])
  quantiles$n20theta.3.2[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 < b20.3.2 & df_nt$n20theta.3 > b20.3.1])
  quantiles$n20theta.3.3[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 < b20.3.3 & df_nt$n20theta.3 > b20.3.2])
  quantiles$n20theta.3.4[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 < b20.3.4 & df_nt$n20theta.3 > b20.3.3])
  quantiles$n20theta.3.5[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 < b20.3.5 & df_nt$n20theta.3 > b20.3.4])
  quantiles$n20theta.3.6[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 < b20.3.6 & df_nt$n20theta.3 > b20.3.5])
  quantiles$n20theta.3.7[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 < b20.3.7 & df_nt$n20theta.3 > b20.3.6])
  quantiles$n20theta.3.8[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 < b20.3.8 & df_nt$n20theta.3 > b20.3.7])
  quantiles$n20theta.3.9[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 < b20.3.9 & df_nt$n20theta.3 > b20.3.8])
  quantiles$n20theta.31[h] <- length(df_nt$n20theta.3[df_nt$n20theta.3 > b20.3.9])
  
  #n = 20 theta = .35
  quantiles$n20theta.35.1[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 < b20.35.1])
  quantiles$n20theta.35.2[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 < b20.35.2 & df_nt$n20theta.35 > b20.35.1])
  quantiles$n20theta.35.3[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 < b20.35.3 & df_nt$n20theta.35 > b20.35.2])
  quantiles$n20theta.35.4[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 < b20.35.4 & df_nt$n20theta.35 > b20.35.3])
  quantiles$n20theta.35.5[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 < b20.35.5 & df_nt$n20theta.35 > b20.35.4])
  quantiles$n20theta.35.6[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 < b20.35.6 & df_nt$n20theta.35 > b20.35.5])
  quantiles$n20theta.35.7[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 < b20.35.7 & df_nt$n20theta.35 > b20.35.6])
  quantiles$n20theta.35.8[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 < b20.35.8 & df_nt$n20theta.35 > b20.35.7])
  quantiles$n20theta.35.9[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 < b20.35.9 & df_nt$n20theta.35 > b20.35.8])
  quantiles$n20theta.351[h] <- length(df_nt$n20theta.35[df_nt$n20theta.35 > b20.35.9])
  
  #n = 20 theta = .4
  quantiles$n20theta.4.1[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 < b20.4.1])
  quantiles$n20theta.4.2[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 < b20.4.2 & df_nt$n20theta.4 > b20.4.1])
  quantiles$n20theta.4.3[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 < b20.4.3 & df_nt$n20theta.4 > b20.4.2])
  quantiles$n20theta.4.4[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 < b20.4.4 & df_nt$n20theta.4 > b20.4.3])
  quantiles$n20theta.4.5[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 < b20.4.5 & df_nt$n20theta.4 > b20.4.4])
  quantiles$n20theta.4.6[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 < b20.4.6 & df_nt$n20theta.4 > b20.4.5])
  quantiles$n20theta.4.7[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 < b20.4.7 & df_nt$n20theta.4 > b20.4.6])
  quantiles$n20theta.4.8[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 < b20.4.8 & df_nt$n20theta.4 > b20.4.7])
  quantiles$n20theta.4.9[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 < b20.4.9 & df_nt$n20theta.4 > b20.4.8])
  quantiles$n20theta.41[h] <- length(df_nt$n20theta.4[df_nt$n20theta.4 > b20.4.9])
  
  #n = 25 theta = .05
  quantiles$n25theta.05.1[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 < b25.05.1])
  quantiles$n25theta.05.2[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 < b25.05.2 & df_nt$n25theta.05 > b25.05.1])
  quantiles$n25theta.05.3[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 < b25.05.3 & df_nt$n25theta.05 > b25.05.2])
  quantiles$n25theta.05.4[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 < b25.05.4 & df_nt$n25theta.05 > b25.05.3])
  quantiles$n25theta.05.5[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 < b25.05.5 & df_nt$n25theta.05 > b25.05.4])
  quantiles$n25theta.05.6[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 < b25.05.6 & df_nt$n25theta.05 > b25.05.5])
  quantiles$n25theta.05.7[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 < b25.05.7 & df_nt$n25theta.05 > b25.05.6])
  quantiles$n25theta.05.8[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 < b25.05.8 & df_nt$n25theta.05 > b25.05.7])
  quantiles$n25theta.05.9[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 < b25.05.9 & df_nt$n25theta.05 > b25.05.8])
  quantiles$n25theta.051[h] <- length(df_nt$n25theta.05[df_nt$n25theta.05 > b25.05.9])
  
  #n = 25 theta = .1
  quantiles$n25theta.1.1[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 < b25.1.1])
  quantiles$n25theta.1.2[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 < b25.1.2 & df_nt$n25theta.1 > b25.1.1])
  quantiles$n25theta.1.3[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 < b25.1.3 & df_nt$n25theta.1 > b25.1.2])
  quantiles$n25theta.1.4[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 < b25.1.4 & df_nt$n25theta.1 > b25.1.3])
  quantiles$n25theta.1.5[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 < b25.1.5 & df_nt$n25theta.1 > b25.1.4])
  quantiles$n25theta.1.6[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 < b25.1.6 & df_nt$n25theta.1 > b25.1.5])
  quantiles$n25theta.1.7[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 < b25.1.7 & df_nt$n25theta.1 > b25.1.6])
  quantiles$n25theta.1.8[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 < b25.1.8 & df_nt$n25theta.1 > b25.1.7])
  quantiles$n25theta.1.9[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 < b25.1.9 & df_nt$n25theta.1 > b25.1.8])
  quantiles$n25theta.11[h] <- length(df_nt$n25theta.1[df_nt$n25theta.1 > b25.1.9])
  
  #n = 25 theta = .15
  quantiles$n25theta.15.1[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 < b25.15.1])
  quantiles$n25theta.15.2[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 < b25.15.2 & df_nt$n25theta.15 > b25.15.1])
  quantiles$n25theta.15.3[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 < b25.15.3 & df_nt$n25theta.15 > b25.15.2])
  quantiles$n25theta.15.4[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 < b25.15.4 & df_nt$n25theta.15 > b25.15.3])
  quantiles$n25theta.15.5[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 < b25.15.5 & df_nt$n25theta.15 > b25.15.4])
  quantiles$n25theta.15.6[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 < b25.15.6 & df_nt$n25theta.15 > b25.15.5])
  quantiles$n25theta.15.7[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 < b25.15.7 & df_nt$n25theta.15 > b25.15.6])
  quantiles$n25theta.15.8[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 < b25.15.8 & df_nt$n25theta.15 > b25.15.7])
  quantiles$n25theta.15.9[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 < b25.15.9 & df_nt$n25theta.15 > b25.15.8])
  quantiles$n25theta.151[h] <- length(df_nt$n25theta.15[df_nt$n25theta.15 > b25.15.9])
  
  #n = 25 theta = .2
  quantiles$n25theta.2.1[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 < b25.2.1])
  quantiles$n25theta.2.2[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 < b25.2.2 & df_nt$n25theta.2 > b25.2.1])
  quantiles$n25theta.2.3[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 < b25.2.3 & df_nt$n25theta.2 > b25.2.2])
  quantiles$n25theta.2.4[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 < b25.2.4 & df_nt$n25theta.2 > b25.2.3])
  quantiles$n25theta.2.5[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 < b25.2.5 & df_nt$n25theta.2 > b25.2.4])
  quantiles$n25theta.2.6[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 < b25.2.6 & df_nt$n25theta.2 > b25.2.5])
  quantiles$n25theta.2.7[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 < b25.2.7 & df_nt$n25theta.2 > b25.2.6])
  quantiles$n25theta.2.8[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 < b25.2.8 & df_nt$n25theta.2 > b25.2.7])
  quantiles$n25theta.2.9[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 < b25.2.9 & df_nt$n25theta.2 > b25.2.8])
  quantiles$n25theta.21[h] <- length(df_nt$n25theta.2[df_nt$n25theta.2 > b25.2.9])
  
  #n = 25 theta = .25
  quantiles$n25theta.25.1[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 < b25.25.1])
  quantiles$n25theta.25.2[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 < b25.25.2 & df_nt$n25theta.25 > b25.25.1])
  quantiles$n25theta.25.3[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 < b25.25.3 & df_nt$n25theta.25 > b25.25.2])
  quantiles$n25theta.25.4[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 < b25.25.4 & df_nt$n25theta.25 > b25.25.3])
  quantiles$n25theta.25.5[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 < b25.25.5 & df_nt$n25theta.25 > b25.25.4])
  quantiles$n25theta.25.6[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 < b25.25.6 & df_nt$n25theta.25 > b25.25.5])
  quantiles$n25theta.25.7[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 < b25.25.7 & df_nt$n25theta.25 > b25.25.6])
  quantiles$n25theta.25.8[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 < b25.25.8 & df_nt$n25theta.25 > b25.25.7])
  quantiles$n25theta.25.9[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 < b25.25.9 & df_nt$n25theta.25 > b25.25.8])
  quantiles$n25theta.251[h] <- length(df_nt$n25theta.25[df_nt$n25theta.25 > b25.25.9])
  
  #n = 25 theta = .3
  quantiles$n25theta.3.1[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 < b25.3.1])
  quantiles$n25theta.3.2[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 < b25.3.2 & df_nt$n25theta.3 > b25.3.1])
  quantiles$n25theta.3.3[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 < b25.3.3 & df_nt$n25theta.3 > b25.3.2])
  quantiles$n25theta.3.4[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 < b25.3.4 & df_nt$n25theta.3 > b25.3.3])
  quantiles$n25theta.3.5[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 < b25.3.5 & df_nt$n25theta.3 > b25.3.4])
  quantiles$n25theta.3.6[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 < b25.3.6 & df_nt$n25theta.3 > b25.3.5])
  quantiles$n25theta.3.7[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 < b25.3.7 & df_nt$n25theta.3 > b25.3.6])
  quantiles$n25theta.3.8[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 < b25.3.8 & df_nt$n25theta.3 > b25.3.7])
  quantiles$n25theta.3.9[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 < b25.3.9 & df_nt$n25theta.3 > b25.3.8])
  quantiles$n25theta.31[h] <- length(df_nt$n25theta.3[df_nt$n25theta.3 > b25.3.9])
  
  #n = 25 theta = .35
  quantiles$n25theta.35.1[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 < b25.35.1])
  quantiles$n25theta.35.2[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 < b25.35.2 & df_nt$n25theta.35 > b25.35.1])
  quantiles$n25theta.35.3[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 < b25.35.3 & df_nt$n25theta.35 > b25.35.2])
  quantiles$n25theta.35.4[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 < b25.35.4 & df_nt$n25theta.35 > b25.35.3])
  quantiles$n25theta.35.5[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 < b25.35.5 & df_nt$n25theta.35 > b25.35.4])
  quantiles$n25theta.35.6[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 < b25.35.6 & df_nt$n25theta.35 > b25.35.5])
  quantiles$n25theta.35.7[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 < b25.35.7 & df_nt$n25theta.35 > b25.35.6])
  quantiles$n25theta.35.8[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 < b25.35.8 & df_nt$n25theta.35 > b25.35.7])
  quantiles$n25theta.35.9[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 < b25.35.9 & df_nt$n25theta.35 > b25.35.8])
  quantiles$n25theta.351[h] <- length(df_nt$n25theta.35[df_nt$n25theta.35 > b25.35.9])
  
  #n = 25 theta = .4
  quantiles$n25theta.4.1[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 < b25.4.1])
  quantiles$n25theta.4.2[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 < b25.4.2 & df_nt$n25theta.4 > b25.4.1])
  quantiles$n25theta.4.3[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 < b25.4.3 & df_nt$n25theta.4 > b25.4.2])
  quantiles$n25theta.4.4[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 < b25.4.4 & df_nt$n25theta.4 > b25.4.3])
  quantiles$n25theta.4.5[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 < b25.4.5 & df_nt$n25theta.4 > b25.4.4])
  quantiles$n25theta.4.6[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 < b25.4.6 & df_nt$n25theta.4 > b25.4.5])
  quantiles$n25theta.4.7[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 < b25.4.7 & df_nt$n25theta.4 > b25.4.6])
  quantiles$n25theta.4.8[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 < b25.4.8 & df_nt$n25theta.4 > b25.4.7])
  quantiles$n25theta.4.9[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 < b25.4.9 & df_nt$n25theta.4 > b25.4.8])
  quantiles$n25theta.41[h] <- length(df_nt$n25theta.4[df_nt$n25theta.4 > b25.4.9])
  
  #n = 30 theta = .05
  quantiles$n30theta.05.1[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 < b30.05.1])
  quantiles$n30theta.05.2[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 < b30.05.2 & df_nt$n30theta.05 > b30.05.1])
  quantiles$n30theta.05.3[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 < b30.05.3 & df_nt$n30theta.05 > b30.05.2])
  quantiles$n30theta.05.4[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 < b30.05.4 & df_nt$n30theta.05 > b30.05.3])
  quantiles$n30theta.05.5[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 < b30.05.5 & df_nt$n30theta.05 > b30.05.4])
  quantiles$n30theta.05.6[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 < b30.05.6 & df_nt$n30theta.05 > b30.05.5])
  quantiles$n30theta.05.7[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 < b30.05.7 & df_nt$n30theta.05 > b30.05.6])
  quantiles$n30theta.05.8[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 < b30.05.8 & df_nt$n30theta.05 > b30.05.7])
  quantiles$n30theta.05.9[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 < b30.05.9 & df_nt$n30theta.05 > b30.05.8])
  quantiles$n30theta.051[h] <- length(df_nt$n30theta.05[df_nt$n30theta.05 > b30.05.9])
  
  #n = 30 theta = .1
  quantiles$n30theta.1.1[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 < b30.1.1])
  quantiles$n30theta.1.2[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 < b30.1.2 & df_nt$n30theta.1 > b30.1.1])
  quantiles$n30theta.1.3[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 < b30.1.3 & df_nt$n30theta.1 > b30.1.2])
  quantiles$n30theta.1.4[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 < b30.1.4 & df_nt$n30theta.1 > b30.1.3])
  quantiles$n30theta.1.5[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 < b30.1.5 & df_nt$n30theta.1 > b30.1.4])
  quantiles$n30theta.1.6[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 < b30.1.6 & df_nt$n30theta.1 > b30.1.5])
  quantiles$n30theta.1.7[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 < b30.1.7 & df_nt$n30theta.1 > b30.1.6])
  quantiles$n30theta.1.8[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 < b30.1.8 & df_nt$n30theta.1 > b30.1.7])
  quantiles$n30theta.1.9[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 < b30.1.9 & df_nt$n30theta.1 > b30.1.8])
  quantiles$n30theta.11[h] <- length(df_nt$n30theta.1[df_nt$n30theta.1 > b30.1.9])
  
  #n = 30 theta = .15
  quantiles$n30theta.15.1[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 < b30.15.1])
  quantiles$n30theta.15.2[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 < b30.15.2 & df_nt$n30theta.15 > b30.15.1])
  quantiles$n30theta.15.3[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 < b30.15.3 & df_nt$n30theta.15 > b30.15.2])
  quantiles$n30theta.15.4[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 < b30.15.4 & df_nt$n30theta.15 > b30.15.3])
  quantiles$n30theta.15.5[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 < b30.15.5 & df_nt$n30theta.15 > b30.15.4])
  quantiles$n30theta.15.6[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 < b30.15.6 & df_nt$n30theta.15 > b30.15.5])
  quantiles$n30theta.15.7[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 < b30.15.7 & df_nt$n30theta.15 > b30.15.6])
  quantiles$n30theta.15.8[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 < b30.15.8 & df_nt$n30theta.15 > b30.15.7])
  quantiles$n30theta.15.9[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 < b30.15.9 & df_nt$n30theta.15 > b30.15.8])
  quantiles$n30theta.151[h] <- length(df_nt$n30theta.15[df_nt$n30theta.15 > b30.15.9])
  
  #n = 30 theta = .2
  quantiles$n30theta.2.1[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 < b30.2.1])
  quantiles$n30theta.2.2[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 < b30.2.2 & df_nt$n30theta.2 > b30.2.1])
  quantiles$n30theta.2.3[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 < b30.2.3 & df_nt$n30theta.2 > b30.2.2])
  quantiles$n30theta.2.4[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 < b30.2.4 & df_nt$n30theta.2 > b30.2.3])
  quantiles$n30theta.2.5[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 < b30.2.5 & df_nt$n30theta.2 > b30.2.4])
  quantiles$n30theta.2.6[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 < b30.2.6 & df_nt$n30theta.2 > b30.2.5])
  quantiles$n30theta.2.7[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 < b30.2.7 & df_nt$n30theta.2 > b30.2.6])
  quantiles$n30theta.2.8[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 < b30.2.8 & df_nt$n30theta.2 > b30.2.7])
  quantiles$n30theta.2.9[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 < b30.2.9 & df_nt$n30theta.2 > b30.2.8])
  quantiles$n30theta.21[h] <- length(df_nt$n30theta.2[df_nt$n30theta.2 > b30.2.9])
  
  #n = 30 theta = .25
  quantiles$n30theta.25.1[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 < b30.25.1])
  quantiles$n30theta.25.2[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 < b30.25.2 & df_nt$n30theta.25 > b30.25.1])
  quantiles$n30theta.25.3[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 < b30.25.3 & df_nt$n30theta.25 > b30.25.2])
  quantiles$n30theta.25.4[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 < b30.25.4 & df_nt$n30theta.25 > b30.25.3])
  quantiles$n30theta.25.5[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 < b30.25.5 & df_nt$n30theta.25 > b30.25.4])
  quantiles$n30theta.25.6[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 < b30.25.6 & df_nt$n30theta.25 > b30.25.5])
  quantiles$n30theta.25.7[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 < b30.25.7 & df_nt$n30theta.25 > b30.25.6])
  quantiles$n30theta.25.8[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 < b30.25.8 & df_nt$n30theta.25 > b30.25.7])
  quantiles$n30theta.25.9[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 < b30.25.9 & df_nt$n30theta.25 > b30.25.8])
  quantiles$n30theta.251[h] <- length(df_nt$n30theta.25[df_nt$n30theta.25 > b30.25.9])
  
  #n = 30 theta = .3
  quantiles$n30theta.3.1[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 < b30.3.1])
  quantiles$n30theta.3.2[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 < b30.3.2 & df_nt$n30theta.3 > b30.3.1])
  quantiles$n30theta.3.3[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 < b30.3.3 & df_nt$n30theta.3 > b30.3.2])
  quantiles$n30theta.3.4[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 < b30.3.4 & df_nt$n30theta.3 > b30.3.3])
  quantiles$n30theta.3.5[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 < b30.3.5 & df_nt$n30theta.3 > b30.3.4])
  quantiles$n30theta.3.6[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 < b30.3.6 & df_nt$n30theta.3 > b30.3.5])
  quantiles$n30theta.3.7[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 < b30.3.7 & df_nt$n30theta.3 > b30.3.6])
  quantiles$n30theta.3.8[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 < b30.3.8 & df_nt$n30theta.3 > b30.3.7])
  quantiles$n30theta.3.9[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 < b30.3.9 & df_nt$n30theta.3 > b30.3.8])
  quantiles$n30theta.31[h] <- length(df_nt$n30theta.3[df_nt$n30theta.3 > b30.3.9])
  
  #n = 30 theta = .35
  quantiles$n30theta.35.1[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 < b30.35.1])
  quantiles$n30theta.35.2[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 < b30.35.2 & df_nt$n30theta.35 > b30.35.1])
  quantiles$n30theta.35.3[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 < b30.35.3 & df_nt$n30theta.35 > b30.35.2])
  quantiles$n30theta.35.4[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 < b30.35.4 & df_nt$n30theta.35 > b30.35.3])
  quantiles$n30theta.35.5[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 < b30.35.5 & df_nt$n30theta.35 > b30.35.4])
  quantiles$n30theta.35.6[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 < b30.35.6 & df_nt$n30theta.35 > b30.35.5])
  quantiles$n30theta.35.7[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 < b30.35.7 & df_nt$n30theta.35 > b30.35.6])
  quantiles$n30theta.35.8[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 < b30.35.8 & df_nt$n30theta.35 > b30.35.7])
  quantiles$n30theta.35.9[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 < b30.35.9 & df_nt$n30theta.35 > b30.35.8])
  quantiles$n30theta.351[h] <- length(df_nt$n30theta.35[df_nt$n30theta.35 > b30.35.9])
  
  #n = 30 theta = .4
  quantiles$n30theta.4.1[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 < b30.4.1])
  quantiles$n30theta.4.2[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 < b30.4.2 & df_nt$n30theta.4 > b30.4.1])
  quantiles$n30theta.4.3[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 < b30.4.3 & df_nt$n30theta.4 > b30.4.2])
  quantiles$n30theta.4.4[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 < b30.4.4 & df_nt$n30theta.4 > b30.4.3])
  quantiles$n30theta.4.5[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 < b30.4.5 & df_nt$n30theta.4 > b30.4.4])
  quantiles$n30theta.4.6[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 < b30.4.6 & df_nt$n30theta.4 > b30.4.5])
  quantiles$n30theta.4.7[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 < b30.4.7 & df_nt$n30theta.4 > b30.4.6])
  quantiles$n30theta.4.8[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 < b30.4.8 & df_nt$n30theta.4 > b30.4.7])
  quantiles$n30theta.4.9[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 < b30.4.9 & df_nt$n30theta.4 > b30.4.8])
  quantiles$n30theta.41[h] <- length(df_nt$n30theta.4[df_nt$n30theta.4 > b30.4.9])
  
  #n = 35 theta = .05
  quantiles$n35theta.05.1[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 < b35.05.1])
  quantiles$n35theta.05.2[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 < b35.05.2 & df_nt$n35theta.05 > b35.05.1])
  quantiles$n35theta.05.3[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 < b35.05.3 & df_nt$n35theta.05 > b35.05.2])
  quantiles$n35theta.05.4[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 < b35.05.4 & df_nt$n35theta.05 > b35.05.3])
  quantiles$n35theta.05.5[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 < b35.05.5 & df_nt$n35theta.05 > b35.05.4])
  quantiles$n35theta.05.6[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 < b35.05.6 & df_nt$n35theta.05 > b35.05.5])
  quantiles$n35theta.05.7[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 < b35.05.7 & df_nt$n35theta.05 > b35.05.6])
  quantiles$n35theta.05.8[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 < b35.05.8 & df_nt$n35theta.05 > b35.05.7])
  quantiles$n35theta.05.9[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 < b35.05.9 & df_nt$n35theta.05 > b35.05.8])
  quantiles$n35theta.051[h] <- length(df_nt$n35theta.05[df_nt$n35theta.05 > b35.05.9])
  
  #n = 35 theta = .1
  quantiles$n35theta.1.1[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 < b35.1.1])
  quantiles$n35theta.1.2[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 < b35.1.2 & df_nt$n35theta.1 > b35.1.1])
  quantiles$n35theta.1.3[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 < b35.1.3 & df_nt$n35theta.1 > b35.1.2])
  quantiles$n35theta.1.4[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 < b35.1.4 & df_nt$n35theta.1 > b35.1.3])
  quantiles$n35theta.1.5[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 < b35.1.5 & df_nt$n35theta.1 > b35.1.4])
  quantiles$n35theta.1.6[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 < b35.1.6 & df_nt$n35theta.1 > b35.1.5])
  quantiles$n35theta.1.7[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 < b35.1.7 & df_nt$n35theta.1 > b35.1.6])
  quantiles$n35theta.1.8[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 < b35.1.8 & df_nt$n35theta.1 > b35.1.7])
  quantiles$n35theta.1.9[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 < b35.1.9 & df_nt$n35theta.1 > b35.1.8])
  quantiles$n35theta.11[h] <- length(df_nt$n35theta.1[df_nt$n35theta.1 > b35.1.9])
  
  #n = 35 theta = .15
  quantiles$n35theta.15.1[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 < b35.15.1])
  quantiles$n35theta.15.2[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 < b35.15.2 & df_nt$n35theta.15 > b35.15.1])
  quantiles$n35theta.15.3[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 < b35.15.3 & df_nt$n35theta.15 > b35.15.2])
  quantiles$n35theta.15.4[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 < b35.15.4 & df_nt$n35theta.15 > b35.15.3])
  quantiles$n35theta.15.5[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 < b35.15.5 & df_nt$n35theta.15 > b35.15.4])
  quantiles$n35theta.15.6[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 < b35.15.6 & df_nt$n35theta.15 > b35.15.5])
  quantiles$n35theta.15.7[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 < b35.15.7 & df_nt$n35theta.15 > b35.15.6])
  quantiles$n35theta.15.8[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 < b35.15.8 & df_nt$n35theta.15 > b35.15.7])
  quantiles$n35theta.15.9[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 < b35.15.9 & df_nt$n35theta.15 > b35.15.8])
  quantiles$n35theta.151[h] <- length(df_nt$n35theta.15[df_nt$n35theta.15 > b35.15.9])
  
  #n = 35 theta = .2
  quantiles$n35theta.2.1[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 < b35.2.1])
  quantiles$n35theta.2.2[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 < b35.2.2 & df_nt$n35theta.2 > b35.2.1])
  quantiles$n35theta.2.3[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 < b35.2.3 & df_nt$n35theta.2 > b35.2.2])
  quantiles$n35theta.2.4[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 < b35.2.4 & df_nt$n35theta.2 > b35.2.3])
  quantiles$n35theta.2.5[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 < b35.2.5 & df_nt$n35theta.2 > b35.2.4])
  quantiles$n35theta.2.6[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 < b35.2.6 & df_nt$n35theta.2 > b35.2.5])
  quantiles$n35theta.2.7[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 < b35.2.7 & df_nt$n35theta.2 > b35.2.6])
  quantiles$n35theta.2.8[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 < b35.2.8 & df_nt$n35theta.2 > b35.2.7])
  quantiles$n35theta.2.9[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 < b35.2.9 & df_nt$n35theta.2 > b35.2.8])
  quantiles$n35theta.21[h] <- length(df_nt$n35theta.2[df_nt$n35theta.2 > b35.2.9])
  
  #n = 35 theta = .25
  quantiles$n35theta.25.1[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 < b35.25.1])
  quantiles$n35theta.25.2[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 < b35.25.2 & df_nt$n35theta.25 > b35.25.1])
  quantiles$n35theta.25.3[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 < b35.25.3 & df_nt$n35theta.25 > b35.25.2])
  quantiles$n35theta.25.4[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 < b35.25.4 & df_nt$n35theta.25 > b35.25.3])
  quantiles$n35theta.25.5[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 < b35.25.5 & df_nt$n35theta.25 > b35.25.4])
  quantiles$n35theta.25.6[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 < b35.25.6 & df_nt$n35theta.25 > b35.25.5])
  quantiles$n35theta.25.7[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 < b35.25.7 & df_nt$n35theta.25 > b35.25.6])
  quantiles$n35theta.25.8[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 < b35.25.8 & df_nt$n35theta.25 > b35.25.7])
  quantiles$n35theta.25.9[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 < b35.25.9 & df_nt$n35theta.25 > b35.25.8])
  quantiles$n35theta.251[h] <- length(df_nt$n35theta.25[df_nt$n35theta.25 > b35.25.9])
  
  #n = 35 theta = .3
  quantiles$n35theta.3.1[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 < b35.3.1])
  quantiles$n35theta.3.2[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 < b35.3.2 & df_nt$n35theta.3 > b35.3.1])
  quantiles$n35theta.3.3[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 < b35.3.3 & df_nt$n35theta.3 > b35.3.2])
  quantiles$n35theta.3.4[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 < b35.3.4 & df_nt$n35theta.3 > b35.3.3])
  quantiles$n35theta.3.5[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 < b35.3.5 & df_nt$n35theta.3 > b35.3.4])
  quantiles$n35theta.3.6[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 < b35.3.6 & df_nt$n35theta.3 > b35.3.5])
  quantiles$n35theta.3.7[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 < b35.3.7 & df_nt$n35theta.3 > b35.3.6])
  quantiles$n35theta.3.8[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 < b35.3.8 & df_nt$n35theta.3 > b35.3.7])
  quantiles$n35theta.3.9[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 < b35.3.9 & df_nt$n35theta.3 > b35.3.8])
  quantiles$n35theta.31[h] <- length(df_nt$n35theta.3[df_nt$n35theta.3 > b35.3.9])
  
  #n = 35 theta = .35
  quantiles$n35theta.35.1[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 < b35.35.1])
  quantiles$n35theta.35.2[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 < b35.35.2 & df_nt$n35theta.35 > b35.35.1])
  quantiles$n35theta.35.3[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 < b35.35.3 & df_nt$n35theta.35 > b35.35.2])
  quantiles$n35theta.35.4[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 < b35.35.4 & df_nt$n35theta.35 > b35.35.3])
  quantiles$n35theta.35.5[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 < b35.35.5 & df_nt$n35theta.35 > b35.35.4])
  quantiles$n35theta.35.6[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 < b35.35.6 & df_nt$n35theta.35 > b35.35.5])
  quantiles$n35theta.35.7[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 < b35.35.7 & df_nt$n35theta.35 > b35.35.6])
  quantiles$n35theta.35.8[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 < b35.35.8 & df_nt$n35theta.35 > b35.35.7])
  quantiles$n35theta.35.9[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 < b35.35.9 & df_nt$n35theta.35 > b35.35.8])
  quantiles$n35theta.351[h] <- length(df_nt$n35theta.35[df_nt$n35theta.35 > b35.35.9])
  
  #n = 35 theta = .4
  quantiles$n35theta.4.1[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 < b35.4.1])
  quantiles$n35theta.4.2[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 < b35.4.2 & df_nt$n35theta.4 > b35.4.1])
  quantiles$n35theta.4.3[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 < b35.4.3 & df_nt$n35theta.4 > b35.4.2])
  quantiles$n35theta.4.4[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 < b35.4.4 & df_nt$n35theta.4 > b35.4.3])
  quantiles$n35theta.4.5[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 < b35.4.5 & df_nt$n35theta.4 > b35.4.4])
  quantiles$n35theta.4.6[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 < b35.4.6 & df_nt$n35theta.4 > b35.4.5])
  quantiles$n35theta.4.7[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 < b35.4.7 & df_nt$n35theta.4 > b35.4.6])
  quantiles$n35theta.4.8[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 < b35.4.8 & df_nt$n35theta.4 > b35.4.7])
  quantiles$n35theta.4.9[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 < b35.4.9 & df_nt$n35theta.4 > b35.4.8])
  quantiles$n35theta.41[h] <- length(df_nt$n35theta.4[df_nt$n35theta.4 > b35.4.9])
  
  #n = 40 theta = .05
  quantiles$n40theta.05.1[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 < b40.05.1])
  quantiles$n40theta.05.2[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 < b40.05.2 & df_nt$n40theta.05 > b40.05.1])
  quantiles$n40theta.05.3[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 < b40.05.3 & df_nt$n40theta.05 > b40.05.2])
  quantiles$n40theta.05.4[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 < b40.05.4 & df_nt$n40theta.05 > b40.05.3])
  quantiles$n40theta.05.5[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 < b40.05.5 & df_nt$n40theta.05 > b40.05.4])
  quantiles$n40theta.05.6[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 < b40.05.6 & df_nt$n40theta.05 > b40.05.5])
  quantiles$n40theta.05.7[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 < b40.05.7 & df_nt$n40theta.05 > b40.05.6])
  quantiles$n40theta.05.8[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 < b40.05.8 & df_nt$n40theta.05 > b40.05.7])
  quantiles$n40theta.05.9[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 < b40.05.9 & df_nt$n40theta.05 > b40.05.8])
  quantiles$n40theta.051[h] <- length(df_nt$n40theta.05[df_nt$n40theta.05 > b40.05.9])
  
  #n = 40 theta = .1
  quantiles$n40theta.1.1[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 < b40.1.1])
  quantiles$n40theta.1.2[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 < b40.1.2 & df_nt$n40theta.1 > b40.1.1])
  quantiles$n40theta.1.3[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 < b40.1.3 & df_nt$n40theta.1 > b40.1.2])
  quantiles$n40theta.1.4[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 < b40.1.4 & df_nt$n40theta.1 > b40.1.3])
  quantiles$n40theta.1.5[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 < b40.1.5 & df_nt$n40theta.1 > b40.1.4])
  quantiles$n40theta.1.6[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 < b40.1.6 & df_nt$n40theta.1 > b40.1.5])
  quantiles$n40theta.1.7[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 < b40.1.7 & df_nt$n40theta.1 > b40.1.6])
  quantiles$n40theta.1.8[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 < b40.1.8 & df_nt$n40theta.1 > b40.1.7])
  quantiles$n40theta.1.9[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 < b40.1.9 & df_nt$n40theta.1 > b40.1.8])
  quantiles$n40theta.11[h] <- length(df_nt$n40theta.1[df_nt$n40theta.1 > b40.1.9])
  
  #n = 40 theta = .15
  quantiles$n40theta.15.1[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 < b40.15.1])
  quantiles$n40theta.15.2[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 < b40.15.2 & df_nt$n40theta.15 > b40.15.1])
  quantiles$n40theta.15.3[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 < b40.15.3 & df_nt$n40theta.15 > b40.15.2])
  quantiles$n40theta.15.4[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 < b40.15.4 & df_nt$n40theta.15 > b40.15.3])
  quantiles$n40theta.15.5[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 < b40.15.5 & df_nt$n40theta.15 > b40.15.4])
  quantiles$n40theta.15.6[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 < b40.15.6 & df_nt$n40theta.15 > b40.15.5])
  quantiles$n40theta.15.7[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 < b40.15.7 & df_nt$n40theta.15 > b40.15.6])
  quantiles$n40theta.15.8[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 < b40.15.8 & df_nt$n40theta.15 > b40.15.7])
  quantiles$n40theta.15.9[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 < b40.15.9 & df_nt$n40theta.15 > b40.15.8])
  quantiles$n40theta.151[h] <- length(df_nt$n40theta.15[df_nt$n40theta.15 > b40.15.9])
  
  #n = 40 theta = .2
  quantiles$n40theta.2.1[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 < b40.2.1])
  quantiles$n40theta.2.2[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 < b40.2.2 & df_nt$n40theta.2 > b40.2.1])
  quantiles$n40theta.2.3[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 < b40.2.3 & df_nt$n40theta.2 > b40.2.2])
  quantiles$n40theta.2.4[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 < b40.2.4 & df_nt$n40theta.2 > b40.2.3])
  quantiles$n40theta.2.5[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 < b40.2.5 & df_nt$n40theta.2 > b40.2.4])
  quantiles$n40theta.2.6[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 < b40.2.6 & df_nt$n40theta.2 > b40.2.5])
  quantiles$n40theta.2.7[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 < b40.2.7 & df_nt$n40theta.2 > b40.2.6])
  quantiles$n40theta.2.8[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 < b40.2.8 & df_nt$n40theta.2 > b40.2.7])
  quantiles$n40theta.2.9[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 < b40.2.9 & df_nt$n40theta.2 > b40.2.8])
  quantiles$n40theta.21[h] <- length(df_nt$n40theta.2[df_nt$n40theta.2 > b40.2.9])
  
  #n = 40 theta = .25
  quantiles$n40theta.25.1[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 < b40.25.1])
  quantiles$n40theta.25.2[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 < b40.25.2 & df_nt$n40theta.25 > b40.25.1])
  quantiles$n40theta.25.3[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 < b40.25.3 & df_nt$n40theta.25 > b40.25.2])
  quantiles$n40theta.25.4[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 < b40.25.4 & df_nt$n40theta.25 > b40.25.3])
  quantiles$n40theta.25.5[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 < b40.25.5 & df_nt$n40theta.25 > b40.25.4])
  quantiles$n40theta.25.6[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 < b40.25.6 & df_nt$n40theta.25 > b40.25.5])
  quantiles$n40theta.25.7[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 < b40.25.7 & df_nt$n40theta.25 > b40.25.6])
  quantiles$n40theta.25.8[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 < b40.25.8 & df_nt$n40theta.25 > b40.25.7])
  quantiles$n40theta.25.9[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 < b40.25.9 & df_nt$n40theta.25 > b40.25.8])
  quantiles$n40theta.251[h] <- length(df_nt$n40theta.25[df_nt$n40theta.25 > b40.25.9])
  
  #n = 40 theta = .3
  quantiles$n40theta.3.1[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 < b40.3.1])
  quantiles$n40theta.3.2[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 < b40.3.2 & df_nt$n40theta.3 > b40.3.1])
  quantiles$n40theta.3.3[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 < b40.3.3 & df_nt$n40theta.3 > b40.3.2])
  quantiles$n40theta.3.4[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 < b40.3.4 & df_nt$n40theta.3 > b40.3.3])
  quantiles$n40theta.3.5[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 < b40.3.5 & df_nt$n40theta.3 > b40.3.4])
  quantiles$n40theta.3.6[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 < b40.3.6 & df_nt$n40theta.3 > b40.3.5])
  quantiles$n40theta.3.7[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 < b40.3.7 & df_nt$n40theta.3 > b40.3.6])
  quantiles$n40theta.3.8[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 < b40.3.8 & df_nt$n40theta.3 > b40.3.7])
  quantiles$n40theta.3.9[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 < b40.3.9 & df_nt$n40theta.3 > b40.3.8])
  quantiles$n40theta.31[h] <- length(df_nt$n40theta.3[df_nt$n40theta.3 > b40.3.9])
  
  #n = 40 theta = .35
  quantiles$n40theta.35.1[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 < b40.35.1])
  quantiles$n40theta.35.2[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 < b40.35.2 & df_nt$n40theta.35 > b40.35.1])
  quantiles$n40theta.35.3[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 < b40.35.3 & df_nt$n40theta.35 > b40.35.2])
  quantiles$n40theta.35.4[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 < b40.35.4 & df_nt$n40theta.35 > b40.35.3])
  quantiles$n40theta.35.5[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 < b40.35.5 & df_nt$n40theta.35 > b40.35.4])
  quantiles$n40theta.35.6[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 < b40.35.6 & df_nt$n40theta.35 > b40.35.5])
  quantiles$n40theta.35.7[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 < b40.35.7 & df_nt$n40theta.35 > b40.35.6])
  quantiles$n40theta.35.8[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 < b40.35.8 & df_nt$n40theta.35 > b40.35.7])
  quantiles$n40theta.35.9[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 < b40.35.9 & df_nt$n40theta.35 > b40.35.8])
  quantiles$n40theta.351[h] <- length(df_nt$n40theta.35[df_nt$n40theta.35 > b40.35.9])
  
  #n = 40 theta = .4
  quantiles$n40theta.4.1[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 < b40.4.1])
  quantiles$n40theta.4.2[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 < b40.4.2 & df_nt$n40theta.4 > b40.4.1])
  quantiles$n40theta.4.3[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 < b40.4.3 & df_nt$n40theta.4 > b40.4.2])
  quantiles$n40theta.4.4[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 < b40.4.4 & df_nt$n40theta.4 > b40.4.3])
  quantiles$n40theta.4.5[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 < b40.4.5 & df_nt$n40theta.4 > b40.4.4])
  quantiles$n40theta.4.6[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 < b40.4.6 & df_nt$n40theta.4 > b40.4.5])
  quantiles$n40theta.4.7[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 < b40.4.7 & df_nt$n40theta.4 > b40.4.6])
  quantiles$n40theta.4.8[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 < b40.4.8 & df_nt$n40theta.4 > b40.4.7])
  quantiles$n40theta.4.9[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 < b40.4.9 & df_nt$n40theta.4 > b40.4.8])
  quantiles$n40theta.41[h] <- length(df_nt$n40theta.4[df_nt$n40theta.4 > b40.4.9])
  save(quantiles, file = "chi-square gof data_2.Rdata")
}

```


```{r}
quantiles.long <- gather(quantiles, "string", "value")
```

```{r}
split <- str_split_fixed(quantiles.long$string, "a", 2)
quantiles.long$n <- substring(split[,1], 2, 3)
quantiles.long$quantile <- substring(split[,2], nchar(split[,2]) -1, nchar(split[,2]))
quantiles.long$quantile <- as.double(quantiles.long$quantile)
quantiles.long.100 <- quantiles.long %>%
  filter(quantile == 51|
           quantile == 11|
           quantile == 21|
           quantile == 31|
           quantile == 41)

quantiles.long <- quantiles.long %>%
  filter(quantile == 0.1|
           quantile == 0.2|
           quantile == 0.3|
           quantile == 0.4|
           quantile == 0.5|
           quantile == 0.6|
           quantile == 0.7|
           quantile == 0.8|
           quantile == 0.9)

splitnew <- str_split_fixed(quantiles.long$string, "a", 2)
  
split100 <- str_split_fixed(quantiles.long.100$string, "a", 2)
quantiles.long.100$quantile <- substring(quantiles.long.100$quantile, 2)
quantiles.long$theta <- substring(splitnew[,2], 1, nchar(splitnew[,2]) -2)
quantiles.long.100$theta <- substring(split100[,2], 1, nchar(split100[,2]) - 1)

quantiles.long <- rbind(quantiles.long, quantiles.long.100)
```


```{r}
quantiles.long <- quantiles.long %>%
  select(n, theta, quantile, value)%>%
  arrange(n,theta,quantile)%>%
  mutate("chisq" = ((value - 100)^2)/100)

quantiles.wide <- data.frame("n" = c(rep(10, 800), rep(15, 800), rep(20, 800), rep(25, 800),
                                     rep(30, 800), rep(35, 800), rep(40, 800)),
                             "theta" = rep(c(rep(.05, 100), rep(.1, 100), rep(.15, 100),
                                             rep(.2, 100), rep(.25, 100), rep(.3, 100),
                                             rep(.35, 100), rep(.4, 100)), 7),
                             "q.1" = quantiles.long$chisq[quantiles.long$quantile == .1],
                             "q.2" = quantiles.long$chisq[quantiles.long$quantile == .2],
                             "q.3" = quantiles.long$chisq[quantiles.long$quantile == .3],
                             "q.4" = quantiles.long$chisq[quantiles.long$quantile == .4],
                             "q.5" = quantiles.long$chisq[quantiles.long$quantile == .5],
                             "q.6" = quantiles.long$chisq[quantiles.long$quantile == .6],
                             "q.7" = quantiles.long$chisq[quantiles.long$quantile == .7],
                             "q.8" = quantiles.long$chisq[quantiles.long$quantile == .8],
                             "q.9" = quantiles.long$chisq[quantiles.long$quantile == .9],
                             "q1" = quantiles.long$chisq[quantiles.long$quantile == 1])
  
quantiles.wide_2 <- quantiles.wide %>%
  mutate("chisquare" = q.1 + q.2 + q.3 + q.4 + q.5 + q.6 + q.7 + q.8 + q.9 + q1)%>%
  group_by(n, theta)%>%
  summarise("Chi-Squared" = mean(chisquare))
names(quantiles.wide_2)[2] <- "Theta"
quantiles.wide_2 <- left_join(quantiles.wide_2, df.Rho)
quantiles.wide_2 <- quantiles.wide_2%>%
  filter(fita >0)
save(quantiles.wide_2, file = "chisq gof_2.Rdata")

```



